### ISSUE TITLE
How to create session programmatically

### ISSUE THREAD

**Issue by ngochuu90** [opentok/opentok-android-sdk-samples#100]
Hi

```
 public static final String API_KEY = "xxxxxx";
 public static final String API_SECRET = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
```

How to generate Session ID and TOKEN by programmatically in Android

**Comment by ngochuu90** [comment]
```
// Set the following constants to your OpenTok API key and API secret.
// See https://tokbox.com/account/.
OpenTok sdk = new OpenTok(API_KEY, API_SECRET);
SessionProperties sessionProperties = new SessionProperties.Builder()
  .mediaMode(MediaMode.ROUTED)
  .build();
Session session = sdk.createSession(sessionProperties);
String sessionId = session.getSessionId();
```

not work

**Comment by robjperez** [comment]
Creating the session from the Android App is not a recommended practice.
Doing that, will require to bundle the `API_SECRET` inside your app and some third party could get it and use it without permission.

The recommended way is to setup a server side where you will get the sessions using the appropriate server sdk. The Android app will communicate with it to fetch the sessionId and the token.

For more details, please take a look to our current tutorial:
https://tokbox.com/developer/tutorials/android/

**Comment by marinaserranomontes** [comment]
Hi @nhoxbypass,

Please, take a look at the tutorial: https://tokbox.com/developer/tutorials/android/basic-video-chat/#server

**Comment by nhoxbypass** [comment]
Thanks @marinaserranomontes so we must use server sdk anyway. Client sdk cannot generate session id.

**Comment by marinaserranomontes** [comment]
Exactly. You have to use the server for a production application. You should not hardcode the credentials in your production app because the sessionIds cannot be created dynamically and tokens expire.

**Comment by nhoxbypass** [comment]
Thank you very much, the documents about Server SDK is also too good. Many thanks~
