### ISSUE TITLE
Project 4: Screen Sharing- Unable to share screen without webview ? 

### ISSUE THREAD

**Issue by devsideal** [opentok/opentok-android-sdk-samples#104]
Using WebView screen is sharing well but when I'm trying to share my app screen that does not have any webview its showing just a blank black screen not showing my shared layout to other user,
We can't share a screen without Web View ?

**Comment by robjperez** [comment]
@devsideal Yes you can share anything you have in a View. Usually you will want to use MediaProjection and use their frames to build a custom capturer.

In any case, please take a look to this repo: https://github.com/opentok/screen-sharing-acc-pack/tree/master/android

It contains a small library that will help you when sharing your screen if you don't want to mess with Custom Capturers and Media Projection API

**Comment by shuBomb** [comment]
I am unable to check url its say 404 and I am getting same issue

**Comment by Niheke** [comment]
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Screen-Sharing
