### ISSUE TITLE
How can i on flash in this library

### ISSUE THREAD

**Issue by shankarpilli** [opentok/opentok-android-sdk-samples#110]
Hi , In the publisher your not giving camera object. How can i on my flash.

Please help on this to solve my requirement. 

ThankYou
Shankar

**Comment by robjperez** [comment]
At this point there are two ways to achieve this:
1. If you target API_LEVEL >= 23, you can enable Camera2 usage in our SDK and use Camera2 API to light the flash.

To enable Camera2 API, you need to use [SessionOptions](https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html) when building the opentok Session object. 

Once you are using Camera2, you can turn the flash on by calling:
```

**Comment by eugenio35** [comment]
Hi @robjperez 

I'm using `opentok-android-sdk:2.16.6` and I'm adding Camera2 usage via sessions options like:

```
val options = object : Session.SessionOptions() {
     override fun isCamera2Capable(): Boolean = true
}

Session.Builder(context, apiKey, sessionId).sessionOptions(options).build().connect(token)
```

But I'm not able to turn the flash on using your suggestion:

```
CameraManager cm = (CameraManager)getSystemService(CAMERA_SERVICE);
try {
  cm.setTorchMode(cm.getCameraIdList()[0], true);
} catch (Exception ex) {
  ex.printStackTrace();
}
```

However if I call onPause() on the Session object, and then turn the flash on. It works fine until I call onResume() and then the flash dies again. 

Is there anyway we can accomplish this in an easy way without using a CustomVideoCapturer for this functionality? 

Are they any plans in the near future to include this functionality inside the CaptureSwitch interface? 

Thanks
