### ISSUE TITLE
SubscriberViewContaine Is Gone when  PublisherViewContainer is match_parent (FullScreen)

### ISSUE THREAD

**Issue by ateek** [opentok/opentok-android-sdk-samples#115]
<RelativeLayout
 xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:keepScreenOn="true"
                android:paddingBottom="16dp"
                android:paddingLeft="16dp"
                android:paddingRight="16dp"
                android:paddingTop="16dp">

    <FrameLayout
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

        <FrameLayout
            android:id="@+id/publisherview"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent">
        </FrameLayout>

        <FrameLayout
            android:id="@+id/subscriberview"
            android:layout_width="150dp"
            android:layout_height="150dp"
            android:layout_gravity="bottom|end"
            android:layout_marginBottom="16dp"
            android:layout_marginEnd="16dp"
            android:background="@color/grey_3"
            android:padding="16dp"/>
    </FrameLayout>

</RelativeLayout>

**Comment by ateek** [comment]
![device-2017-05-02-145301](https://cloud.githubusercontent.com/assets/6179699/25627064/c18f738a-2f61-11e7-9136-4a69ded3c0fa.png)

**Comment by ateek** [comment]
I fixed this by doing that 
   GLSurfaceView subscriberView = (GLSurfaceView) subscriber.getView();
            subscriberView.setZOrderMediaOverlay(true);
            subscriberView.setZOrderOnTop(true);

**Comment by robjperez** [comment]
Due to the behaviour of GLSurfaceViews you need to explicitly set the order of each view, 

Like you have already pointed out, the solution is to do something similar to this: https://github.com/opentok/opentok-android-sdk-samples/blob/master/OpenTokSamples/1.Hello-World/src/main/java/com/opentok/android/samples/hello_world/MainActivity.java#L162

**Comment by mstar0125** [comment]
Hi @robjperez 
Your url is not working. Could you please explain again?
