### ISSUE TITLE
New `PublisherKit.Builder.audioBitrate(bitsPerSecond)` method should be exposed on `Publisher.Builder`

### ISSUE THREAD

**Issue by sschendel** [opentok/opentok-android-sdk-samples#122]
Version 2.11.0.

Cannot set audio bit rate using `Publisher.Builder` now.  Should expose new `PublisherKit.Builder.audioBitrate(bitsPerSecond)` method on `Publisher.Builder`.

Be nice if this feature's use was added to one of the sample projects too.

**Comment by jeffswartz** [comment]
Hey, @sschendel. The `Publisher.Builder` class inherits from the `PublisherKit.Builder` class, so it inherits the `PublisherKit.Builder.audioBitrate(bitsPerSecond)` method.

However, you are right: the samples do not illustrate the use of all of the `Publisher.Builder` methods.

**Comment by sschendel** [comment]
@jeffswartz `Publisher.Builder` class cannot use the parent method as the fluent method returns wrong type (`PublisherKit.Builder` not `Publisher.Builder`).

https://gyazo.com/4c6688b749a91d0a43515858fc1f71f3

**Comment by marinaserranomontes** [comment]
@sschendel yes, the method is there for the PublisherKit but we have to add it also to the Publisher builder to return the right type of the builder. We have added it to the backlog.
Thanks.
