### ISSUE TITLE
corewebrtc support in sample app

### ISSUE THREAD

**Issue by osamakhn** [opentok/opentok-android-sdk-samples#123]
I am trying to extend the android sample app and add core webrtc support such that my app can failover to a secondary managed coturn server in case tokbox services fail. Is there a way I can either use core webrtc or use tokbox sdk to talk to custom coturn servers as having both libs in the same project leads to conflicts.

**Comment by marinaserranomontes** [comment]
hi @osamakhn, we have not tested this scenario. But probably, you will have some conflicts with the libjingle.jar
