### ISSUE TITLE
PublisherView disappear after resume

### ISSUE THREAD

**Issue by mstar0125** [opentok/opentok-android-sdk-samples#130]
Publisher view is showing initially when creating and publishing stream. But after activity resume from sleep mode, it is disappeared.

Please tell me how to set order for each view to keep publisher view show always

**Comment by marinaserranomontes** [comment]
@mstar0125 with the current samples, I am not able to reproduce your case. But please note, if you use GLSurfaceView, you need to set the order of each view:
    if (mPublisher.getView() instanceof GLSurfaceView) {
            ((GLSurfaceView)(mPublisher.getView())).setZOrderOnTop(true);
    }
