### ISSUE TITLE
Record local video

### ISSUE THREAD

**Issue by AnkanDey88** [opentok/opentok-android-sdk-samples#131]
How can I save the local video only in my device SD-Card. I don't want to use the web end-points to save it in server.  Any help is highly appreciable. Thanks in advance.

**Comment by marinaserranomontes** [comment]
Hi @AnkanDey88,

Using Tokbox archiving feature you can store your recorded videos to:

1. Amazon S3 bucket or Windows Azure container    or
2. OpenTok cloud

You can download the archives from both the locations when archives are successfully uploaded. More info here: https://tokbox.com/developer/guides/archiving/

**Comment by AnkanDey88** [comment]
Hi @marinaserranomontes

Thank you for letting me know on this. But is there any other way to save local video instead of the Tokbox archiving feature. May be we can use MediaRecorder.
Please let me know on this.

**Comment by marinaserranomontes** [comment]
Hi @AnkanDey88,

Yes, you could try to use MediaRecorder with TextureViews.

**Comment by AnkanDey88** [comment]
Hi @marinaserranomontes

I have tried to use this. But no result. When I use MediaRecorder, then camera freezes and opponent sees my still image.
If it is possible to use MediaRecorder with TextureViews then please give me any tutorials for that.

Thanks in advance.

**Comment by marinaserranomontes** [comment]
Hi @AnkanDey88,

I think you could try 2 approaches:

- If you wan to record entire screen, you could use the MediaRecorder and MediaProjection
- If you only want to record the publisher stream, you could implement a CustomVideoCapturer, where you can manage the mediaRecorder and the Camera.
Find an example about how to manage a CustomVideoCapturer here: https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Video-Driver

**Comment by AnkanDey88** [comment]
Hi @marinaserranomontes

I did exactly the same thing which you mentioned in 2nd point. But I'm facing one problem is that, when I start video recording using MediaRecorder I have to unlock the camera first and so that the camera stream freezes for TokBox.

mediaRecorder = new MediaRecorder();
mediaRecorder.setCamera(myCamera); // This camera object got fromCustomVideoCapturer
myCamera.unlock();
mediaRecorder.setAudioSource(MediaRecorder.AudioSource.CAMCORDER);
mediaRecorder.setVideoSource(MediaRecorder.VideoSource.CAMERA);
mediaRecorder.setProfile(CamcorderProfile.get(CamcorderProfile.QUALITY_LOW));
mediaRecorder.setOutputFile("/sdcard/video.mp4");
mediaRecorder.setMaxDuration(60000); // Set max duration 60 sec.
mediaRecorder.setMaxFileSize(5000000); // Set max file size 5M
        try {
            mediaRecorder.prepare();
            mediaRecorder.start();
        } catch (IllegalStateException e) {
            return false;
        } catch (IOException e) {
            return false;
        }

**Comment by marinaserranomontes** [comment]
Hi @AnkanDey88 ,

To use TextureViews you need to indicate it in the SessionOptions.
https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html

Eg: 
mSession = new Session(MainActivity.this, APIKEY, SESSION_ID, new Session.SessionOptions() {

  @Override
   public boolean useTextureViews() {
      return true;
   }
  });

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed. 

Please reopen if you still encounter this issue You can also contribute directly by providing a patch.

Thank you!
