### ISSUE TITLE
SessionListener.onStreamReceived not called

### ISSUE THREAD

**Issue by lby1992** [opentok/opentok-android-sdk-samples#132]
I'm building my android application with  `com.opentok.android:opentok-android-sdk:2.11.0` .
below is my code in `SubscriberActivity`:
```
  @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_live_subscriber);

        initView();

        queryToken();
    }
    //success on server response
    private void onTokenReceived(String apiKey, String sessionId, String token) {
         liveSession = new Session.Builder(this, apiKey, sessionId).build();
        liveSession.setSessionListener(this);
        liveSession.connect(token);
    }
     @Override
        public void onStreamReceived(Session session, Stream stream) {
            if (liveSubscriber == null) {
                liveSubscriber = new Subscriber.Builder(this, stream).build();
                liveSubscriber.getRenderer().setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FILL);
                session.subscribe(liveSubscriber);
                showPlayingView();
                liveSubscriberView.addView(liveSubscriber.getView());
            } 
        }
```
I entered this screen and `SessionListener.onConnected(Session)` had been called, but `onStreamReceived` never called.

This problem is serious for me, please give me help, thanks.

**Comment by marinaserranomontes** [comment]
Hi @lby1992,

Please note, the "onStreamReceived(Session session, Stream stream) event, will be invoked when you are connected to the session and there is a new stream published by another client in the same OpenTok session.

Do you have another participant connected to this OpenTok session?

**Comment by lby1992** [comment]
@marinaserranomontes Thanks for your reply. 
I had published a stream yet and it was stopped before I try to subscribe it. On iOS client it can be watched, but android client can't.

**Comment by lby1992** [comment]
I found the reason, I should use the saved video url to watch the video which no longer live active. @marinaserranomontes thank you.
