### ISSUE TITLE
SIP demo?

### ISSUE THREAD

**Issue by dj-4war** [opentok/opentok-android-sdk-samples#135]
We are looking for SIP sample project? I don't see any project that is related to SIP in the list. If  we have one please share.

**Comment by marinaserranomontes** [comment]
Hi @dj-4war ,

We don't have any public SIP sample in Android.
But you can find the details of the REST API for OpenTok SIP  here: https://tokbox.com/developer/guides/sip/

**Comment by dj-4war** [comment]
We are using vopip.ms, our use case is to initiate the call from Android client using TokBox to PSTN/Mobile#.
