### ISSUE TITLE
Subscriber view in front of Publisher view

### ISSUE THREAD

**Issue by sebastianmarschall** [opentok/opentok-android-sdk-samples#136]
I'm trying to achieve that the Subscriber view is in a small layout in front of Publisher view. Basically like in the Basic-Video-Chat sample but only vice-versa.

It works perfectly on my Nexus 6P but when using a Nexus 5 the small subscriber view gets transparent as soon as the chat partner connects - leaving only the white corner around the FrameLayout.

Reproduce: 

1. check out the Basic-Video-Chat sample project
2. open the MainActivity layout file ("activity-main.xml")
3. switch the ids of the containers (@+id/publisher_container & @+id/subscriber_container)
4. run on older?/weaker? device (can confirm for Nexus 5 and Moto G3)

**Comment by sebastianmarschall** [comment]
duplicate of issue#115, sorry

**Comment by sebastianmarschall** [comment]
Reopening because #115 did not solve my problem.
`subscriberView.setZOrderOnTop(true);` does not do the trick for me because then the subscriber view is also in front of all other gui elements.
Using only `subscriberView.setZOrderMediaOverlay(true);` does not solve the original issue (the subsriber view is not visible, see first post in this issue)

**Comment by marinaserranomontes** [comment]
Hi @sebastianmarschall 

Try using TextureViews instead of GLSurfaceView, which is what OpenTok sdk uses by default.

To enable TextureViews, you need to build the session in this way:
Session session = new Session.Builder(this, "apiKey", "sessionId")
    .sessionOptions(new Session.SessionOptions() {
      @Override
      public boolean useTextureViews() {
        return true;
      }
    }).build();

Take a look to the doc: https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html#SessionOptions--

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!

**Comment by asatour** [comment]
Hello, 
I managed to resolve this problem by using Modal (that I make visible only when the subscriber is connected)

```
renderTocKBox() {
    const tokboxStyle =
      {
        publisher: {
          width: 100,
          height: 100,
          position: 'absolute',
          top: 220,
          left: 10,
          backgroundColor: 'red',
          zIndex: 30,
        },
        subscriber: {
          backgroundColor: 'yellow',
          width: 400,
          height: 400,
        },
      }

    const {tokboxProToken, tokboxSessionId, tokboxApiKey} = this.props.teleconsultation
    return (

      <View>
        <OTSession
          apiKey={tokboxApiKey}
          sessionId={tokboxSessionId}
          token={tokboxProToken}
          onError={this.onSessionError}
          eventHandlers={this.sessionEventHandlers}
        >
          <View>
            <Modal
              animationType="slide"
              transparent
              visible={this.state.connection === this.STATUS.SUBSCRIBER_CONNECTED}
            >
              <OTPublisher
                properties={{width: 100, height: 100}}
                style={tokboxStyle.publisher}
                onPublish={this.onPublish}
                onError={this.onPublishError}
                eventHandlers={this.publisherEventHandlers}
              />
            </Modal>
            <OTSubscriber
              properties={{width: 400, height: 400}}
              style={tokboxStyle.subscriber}
              onSubscribe={this.onSubscribe}
              onError={this.onSubscribeError}
              eventHandlers={this.subscriberEventHandlers}
            />

          </View>
        </OTSession>
      </View>

    )
  }

```

**Comment by asatour** [comment]
I've posted the solution here: [(https://github.com/opentok/opentok-react-native/issues/122#issuecomment-409209518)]

**Comment by asatour** [comment]
I've posted the solution here: [https://github.com/opentok/opentok-react-native/issues/122#issuecomment-409209518](https://github.com/opentok/opentok-react-native/issues/122#issuecomment-409209518)
