### ISSUE TITLE
Archive video could not be full screen

### ISSUE THREAD

**Issue by lby1992** [opentok/opentok-android-sdk-samples#140]
HI, I face some problems of playing archive video.
After I publishing the stream, I get the archive url from server. But, in chrome or by android `VideoView` , the archive video could not toggle full screen, video content just kept the origin size.
![full screen mode in chrome](https://user-images.githubusercontent.com/7285065/28636749-bb1fb8fe-7271-11e7-9feb-282a3de0cc22.png)
but in safari, the video can fill the window:
![normal mode in safari](https://user-images.githubusercontent.com/7285065/28636819-fa3b8d4c-7271-11e7-8325-c7f4957e3253.jpg)
![full screen mode in safari](https://user-images.githubusercontent.com/7285065/28636836-12528a52-7272-11e7-8d09-d76f10b5d508.jpg)
is there anyone could help me, thanks.

**Comment by lby1992** [comment]
I analyzed basic information of the archive video, and found that width(640) was greater than height(480)
![basic information](https://user-images.githubusercontent.com/7285065/28639342-76dd626e-727a-11e7-9c52-fe58d2399422.png)
So, I guess there are black blocks at left and right side of the content

**Comment by marinaserranomontes** [comment]
Hi @lby1992 ,

Regarding archiving, composed archives have a fixed dimension of VGA (640x480). If you prefer to capture the full published resolution, consider evaluating individual stream archiving.

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!
