### ISSUE TITLE
group video calling

### ISSUE THREAD

**Issue by monikarora** [opentok/opentok-android-sdk-samples#141]
Hey @opentok-porter  , i want to add group video in app . your app is provide group video calling ?

**Comment by marinaserranomontes** [comment]
Hi @monikarora,

Take a look to the following multiparty samples:
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Simple-Multiparty
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Multiparty-ConstraintLayout

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!
