### ISSUE TITLE
Alternative of event.stream.connection.data for ANDROID in TOKBOX

### ISSUE THREAD

**Issue by Git-Ajay** [opentok/opentok-android-sdk-samples#142]
I want to get additional data of stream which I added during token create. I'm getting additional data in web but not in Android Tokbox.

**Comment by marinaserranomontes** [comment]
Hi @Git-Ajay ,

You can get it using the method "public java.lang.String getData()" in the Connection class. Eg: myConnection.getData().

https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Connection.html

It will return a string containing metadata describing the connection. You can add this connection data when you create a token.

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!
