### ISSUE TITLE
How mSurfaceTexture setup affects on the Capturer?

### ISSUE THREAD

**Issue by luckcoolla** [opentok/opentok-android-sdk-samples#144]
Why do you need these lines in the https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Video-Driver expample:

`  mSurfaceTexture = new SurfaceTexture(42);`
`  mCamera.setPreviewTexture(mSurfaceTexture);`

**Comment by marinaserranomontes** [comment]
Hi @luckcoolla,

We need these lines to create the SurfaceTexture, and to set it to be used for the preview.

Regarding the ’42' value, it is the OpenGL texture name. Any nonzero unsigned integer may be used as a texture name. Just to avoid to use a reserved name, we have set ’42’. Alternatively, to avoid accidentally reusing names, you can use glGenTextures() to provide unused texture names.

Best,
Marina
