### ISSUE TITLE
Problem with GLSurfaceView Z order 

### ISSUE THREAD

**Issue by fedoretskn** [opentok/opentok-android-sdk-samples#145]
If I remove publisher view from screen and add it again this view will show subscriber's video.
It happens because subscriber and publisher by default use `GLSurfaceView` and set ZOrder in media overlay `this.view.setZOrderMediaOverlay(true);`
But Android can't simultaneously show 2 surface views at the same Z order (depth).
https://stackoverflow.com/questions/5647824/android-multiple-surfaceviews/22746240#22746240

It happens also when I remove view container for all these views and add it again in view hierarchy, for example replace 2 controllers in one activity. 

I created diff for `Basic-Video-Chat` which you can use to test this issue but github doesn't accept it so I renamed diff to txt.
[z_order_issue.txt](https://github.com/opentok/opentok-android-sdk-samples/files/1277341/z_order_issue.txt)

**Comment by marinaserranomontes** [comment]
Hi @fedoretskn 

Try using TextureViews instead of GLSurfaceView, which is what OpenTok sdk uses by default.

To enable TextureViews, you need to build the session in this way:
Session session = new Session.Builder(this, "apiKey", "sessionId")
.sessionOptions(new Session.SessionOptions() {
@override
public boolean useTextureViews() {
return true;
}
}).build();

Take a look to the doc: https://tokbox.com/developer/sdks/android/reference/com/opentok/android/Session.SessionOptions.html#SessionOptions--

**Comment by fedoretskn** [comment]
Unfortunately it doesn't work too, in this case both views remain blank after adding to the screen again.
I just added
```
mSession = new Session.Builder(this, apiKey, sessionId).sessionOptions(new Session.SessionOptions() {
            @Override
            public boolean useTextureViews() {
                return true;
            }
        }).build();
```
Note, I used `Basic-Video-Chat` app.

**Comment by robjperez** [comment]
Hi @fedoretskn 

I have been able to reproduce part of your problem.
To fix the Z-Ordering, please take a look to this PR: 
https://github.com/opentok/opentok-android-sdk-samples/pull/146

Basically you can fix it adding ` ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true);` when using SurfaceViews

What I couldn't reproduce is: `It happens also when I remove view container for all these views and add it again in view hierarchy, for example replace 2 controllers in one activity.`

I added your diff to Basic-Video-Chat and the publisher view is placed ok after clicking the button twice.

**Comment by fedoretskn** [comment]
Actually, I did it. 
You fixed this issue only in this sample app, but problem is in **library** so every client that uses your library will face with this problem. You should fix it in library code.

**Comment by robjperez** [comment]
Thanks for your feedback @fedoretskn .

At the library level we don't know how the views are going to be handled by a given developer. Some might want to put the subscriber view on top of the publisher view and setting the publisher zorder on top in the library will break their use cas

**Comment by fedoretskn** [comment]
In this case you should provide way to change Z order without downcasting of views. you should add methods or something else (Builder?) to provide possibility to change z order.

**Comment by alexnik0888** [comment]
> Unfortunately it doesn't work too, in this case both views remain blank after adding to the screen again.
I have the same problem. When I change surface view to TextureView and several times add and remove surface view it doesn't appear again.
