### ISSUE TITLE
MVP, Dagger, Butterknife 🎉

### ISSUE THREAD

**Issue by adrienrx** [opentok/opentok-android-sdk-samples#151]
Hi all, 

I'm wondering if you have plan to create a sample with MVP or MVVM or clean architecture with maybe RxJava/Dagger2/Butterknife? 

Why not a Kotlin sample?

Best,

**Comment by robjperez** [comment]
Hi, thanks for your feedback.

Although it is not official and it was created long time ago, you can find  a kotlin sample here: https://github.com/robjperez/opentok-testmultiparty
