### ISSUE TITLE
Keep the same aspect ratio whenever the screen is landscape or portrait

### ISSUE THREAD

**Issue by lby1992** [opentok/opentok-android-sdk-samples#152]
My app use the `com.opentok.android.Publisher` to create a publisher view, and have two subscriber views on the left side:
![image](https://user-images.githubusercontent.com/7285065/32321426-0f143f70-bffc-11e7-8669-42608d017004.png)
When the screen is protrait, the publisher preview looks having the different aspect ratio, but get the same when the screen is landscape. How should I make the aspect ratio to match other video views?

**Comment by marinaserranomontes** [comment]
Hi @lby1992,

Please take a look to the capturer resolution in landscape and portrait modes and the container size you have. You need to play with them to adjust the image to the desired aspect ratio.

More info:
https://tokbox.com/developer/guides/audio-video/android/#custom_capturer
https://tokbox.com/developer/guides/customize-ui/android/#custom_renderer

**Comment by lby1992** [comment]
Hi, @marinaserranomontes .
I had got the `CustomVideoCapturer.java` from demo code, and set the resolution to 640×480. Under landscape  mode, it looks correctly. But the camera seems captured 480×640 when  the screen rotate to protrait. Can you tell me why?

**Comment by marinaserranomontes** [comment]
Hi @lby1992 ,

In the CustomVideoCapturer we are going to use the closest resolution supported to the preferred setting. And also,  please note, the width and height sizes are based on camera orientation. 
Applications need to consider the display orientation while setting preview size. 
https://developer.android.com/reference/android/hardware/Camera.Parameters.html#setPreviewSize(int,%20int)


Best,
Marina

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly by providing a patch.

Thank you!
