### ISSUE TITLE
Could not find com.opentok.android:opentok-android-sdk:2.10.1-REL-2782.

### ISSUE THREAD

**Issue by tejasna** [opentok/opentok-android-sdk-samples#154]
I have a module(sdk) in my android project that uses opentok internally. Lately my builds are failing on CircleCi with the following error : 
```
> Could not find com.opentok.android:opentok-android-sdk:2.10.1-REL-2782.
           Required by:
               project :identity
```
Works okay locally, but when the build gets generated on CircleCi, i'm getting the above error. It used to work earlier though. Didn't know where to go, appreciate any sort of help.
Thanks in advance.

**Comment by marinaserranomontes** [comment]
Hi @tejasna 

Please, replace the old maven url for this new one "maven { url 'https://tokbox-telefonica.bintray.com/maven' }".

Best,
Marina

**Comment by tejasna** [comment]
Hey @marinaserranomontes 

That did the trick!  You just saved me hours of effort. 
Thank you so much.

**Comment by msach22** [comment]
@tejasna Please keep in mind that this URL has been temporarily changed, we will keep you updated if there are any more changes.

**Comment by msach22** [comment]
@tejasna As of 11/15/17 ~7:45 am PST: We've restored the original URL: https://tokbox.bintray.com/maven/
Please switch back from using the temporary URL to the original URL.

**Comment by tejasna** [comment]
Thanks @msach22, can confirm the original URL `tokbox.bintray.com/maven/` works 👍
