### ISSUE TITLE
Auto focus and log statements

### ISSUE THREAD

**Issue by JayTokBox** [opentok/opentok-android-sdk-samples#156]
Based on partner's request:

Custom Video Driver 
I only found one issue that I think you need to resolve. Auto focus is not enabled for the custom video capturer. I suggest adding:

if (parameters.getSupportedFocusModes().contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO)){ 
parameters.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO); 
}

Before setting the camera parameters in startCapture() 
I also see a lot of warning log statements e.g. "init() entered" + more similar. (link (https://github.com/opentok/opentok-android-sdk-samples/blob/master/Custom-Video-Driver/app/src/main/java/com/tokbox/android/tutorials/custom_video_driver/CustomVideoCapturer.java#L104) ). Better practice to keep them as verbose log statements instead of warnings.

**Comment by marinaserranomontes** [comment]
Thanks for the feedback, @JayTokBox.
Agree, auto focus could be added in the Custom Video Capturer.
Regarding logs, let me take a look.

Best,
Marina

**Comment by marinaserranomontes** [comment]
https://github.com/opentok/opentok-android-sdk-samples/pull/157

**Comment by marinaserranomontes** [comment]
Merged.
