### ISSUE TITLE
Crush with Release Apk

### ISSUE THREAD

**Issue by piseysen** [opentok/opentok-android-sdk-samples#159]
I use opentok with my project, work well with debug but release apk, it is always crush. How Do I build release apk?

**Comment by ajayV1992** [comment]
Hi @piseysen,
I also faced the similar issue where my app get crashed in release mode whereas it was working fine in development mode. 
So, after some digging, I added the following permission in my manifest file
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
and after that the issue was resolved.

Try and see if that works!

**Comment by piseysen** [comment]
Thanks for your try to help me. I added permission like this
android.permission.CAMERA
android.permission.INTERNET
android.permission.RECORD_AUDIO
android.permission.MODIFY_AUDIO_SETTINGS
android.permission.BLUETOOTH
android.permission.BROADCAST_STICKY

But still not work for release apk.

Can u show me the permission that you added to manifest. Thanks

**Comment by marinaserranomontes** [comment]
Hi @piseysen ,

Please, could you detail what is the error you are getting?

Regarding the required permissions, please note, you don't need to add them to your app manifest. The OpenTok SDK adds them automatically. However, if you use Android 21+, certain permissions require you to prompt the user.

Best,
Marina

**Comment by ajayV1992** [comment]
Sorry for that. But I added the permission in my previous post but I don't know how it got removed.
Here is the permissions I have added in my Mobile App.
android.permission.INTERNET
android.permission.RECORD_AUDIO
android.permission.RECORD_VIDEO
android.permission.CAMERA
android.permission.MODIFY_AUDIO_SETTINGS
android.permission.WAKE_LOCK
android.permission.ACCESS_NETWORK_STATE
// This last permission helped me resolve my app crash issue. Still don't know why this permission is necessary in my mobile App
android.permission.SYSTEM_ALERT_WINDOW

Try to add this last permission in your app and see if it helps

**Comment by marinaserranomontes** [comment]
I’m closing this issue. It should have been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!

**Comment by uttam7800** [comment]
Hello Team,

I am getting same issue now a day's, I was working fine before. 

Now when i simple run the application its working fine but if a created a signed apk for release into play store. Its not working. 

I have issue only three permission also handle run time permissions as below

  @AfterPermissionGranted(RC_VIDEO_APP_PERM)
    private void requestPermissions() {
        String[] perms = {
                Manifest.permission.INTERNET,
                Manifest.permission.CAMERA,
                Manifest.permission.RECORD_AUDIO

        };
        if (EasyPermissions.hasPermissions(this, perms)) {
            mSession = new Session.Builder(VideoSessionActivity.this,API_KEY, SESSION_ID).build();
            mSession.setSessionListener(this);
            mSession.connect(TOKEN_ID);
        } else {
            EasyPermissions.requestPermissions(this, getString(R.string.rationale_video_app), RC_VIDEO_APP_PERM, perms);
        }
    } 

Please help me . Thank you in advance
