### ISSUE TITLE
MainActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by akashsoni143786** [opentok/opentok-android-sdk-samples#166]
Activity com.tokbox.android.tutorials.basic_video_chat.MainActivity has leaked IntentReceiver com.opentok.android.DefaultAudioDevice$5@13e0f8a that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                               android.app.IntentReceiverLeaked: Activity com.tokbox.android.tutorials.basic_video_chat.MainActivity has leaked IntentReceiver

**Comment by marinaserranomontes** [comment]
Hi @akashsoni143786 ,

Thanks for your feedback. I am able to reproduce it, so let us review the code for that.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @akashsoni143786 ,

I’m closing this issue because it has been inactive for a few weeks. An improvement for your issue, will be released in the next SDK version.

Please reopen if you still encounter this issue. You can also contribute directly to samples by providing a patch.

Thank you!

**Comment by abdulwaheedandroid** [comment]
I am also facing the same issue. Any help?

**Comment by edwardbrosens** [comment]
So, if anyone stumbles upon this thread after searching for this error.
Set a breakpoint in your onCreate (or if you're using Fragments; where the Fragment is created) and see if it gets executed twice.
You can force the BroadcastReceiver(s) in DefaultAudioDevice to unregister if you call:
`AudioDeviceManager.getAudioDevice().onPause()` (check if AudioDeviceManager.getAudioDevice() is not null first) which will make the error disappear.
But I highly recommend checking double execution first.
