### ISSUE TITLE
Any way to stop user having simultaneous video chat calls with other app (e.g. Skype)?

### ISSUE THREAD

**Issue by markymc** [opentok/opentok-android-sdk-samples#169]
Hi there,

Apologies if this is the wrong place to post this, but I'm having trouble finding any info on my problem.

One of our team was asking if we can stop two video calls happening at the same time. e.g. one using our app (OpenTok SDK) and the other being something like Skype. Either stopping the other call from being started, or stopping our call if Skype starts.

Thanks!

**Comment by marinaserranomontes** [comment]
Hi @markymc ,

Sorry for the late reply. 
Regarding the case you commented, I think the "audio focus" can help to detect this situation.
https://developer.android.com/guide/topics/media-apps/audio-focus
You can implement the AudioManager.OnAudioFocusChangeListener in the CustomAudioDriver class, to detect when the focus is lost.

Best,
Marina

**Comment by markymc** [comment]
Thanks @marinaserranomontes! Will give that a shot. :)

**Comment by marinaserranomontes** [comment]
Hi @markymc ,

I’m closing this issue because it has been inactive for a few weeks.
Please re-open if needed.

Thank you!

Best,
Marina
