### ISSUE TITLE
When using CustomVideoCapturer camera preview is getting disorted (Some red, green color flares are showing)

### ISSUE THREAD

**Issue by dakshays** [opentok/opentok-android-sdk-samples#170]
**Steps to reproduce this issue**
When using CustomVideoCapturer with publisher, The camera preview is getting disorted. Below is the code for the. 
```java
mPublisher = new Publisher.Builder(context).name(String.valueOf(new Me(context).getId()))
                .capturer(new CustomVideoCapturer(this, Publisher.CameraCaptureResolution.HIGH, 
                 Publisher.CameraCaptureFrameRate.FPS_30))
                .build();
        mPublisher.setPublisherListener(this);
        mPublisher.setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FILL);
        mPublisherViewContainer.addView(mPublisher.getView());
```
**What do you see instead?**
Showing Flares and dis-sorted camera preview when using with CustomVideoCapturer
![device-2018-05-22-191802](https://user-images.githubusercontent.com/20255848/40366991-096f4f68-5df6-11e8-9e5d-9158f62665bb.png)

**After sometime, Some red and green color started visible.**
![device-2018-05-22-191901](https://user-images.githubusercontent.com/20255848/40367180-5dffeb3c-5df6-11e8-9fcd-62c54ef9834f.png)

**Expected Output**
![device-2018-05-22-193329](https://user-images.githubusercontent.com/20255848/40367469-2305fe12-5df7-11e8-8098-ae1600cbea69.png)

**Test on OS**
Android 7.0, 8.1 OpenTok SDK is the current one (2.14.0)

**Test Devices**
Yes, Moto C Plus and Nexus 6P, Samsung Galaxy Note 2

**Other Detail**
This is only happening when using CustomVideoCapturer with Publisher. Without it is working good.
I have a requirement for handle camera focusability so need to use camera parameters. And for that CustomVideoCapturer is required. 

Though, I have just copied the CustomVideoCapturer class from your sample project and nothing has been changed yet.

Thank you for your help in Advance.

**Comment by marinaserranomontes** [comment]
hi @dakshays ,

We are testing the CustomVideocapturer samples on Nexus 6P with Android 8.0, and we are not able to reproduce it. Could you give us more details about the changes you are trying to do?

Best,
Marina

**Comment by dakshays** [comment]
Hi Marina,  

Thank you for your reply.

I'm really sorry for that, But it seems like opentok sample are working OK. There must be something wrong with my implementation. I'm checking on it but still not sure where.

I guess issue is with the Renderer. As only preview at publisher end is getting distorted.
I have attached both capturer and renderer files. If you could help.

Regards,



[BasicCustomVideoRenderer.txt](https://github.com/opentok/opentok-android-sdk-samples/files/2114158/BasicCustomVideoRenderer.txt)
[CustomVideoCapturer.txt](https://github.com/opentok/opentok-android-sdk-samples/files/2114159/CustomVideoCapturer.txt)

**Comment by Dermendzhiev** [comment]
Hello Dakshay,

Have you found what the problem was with your implementation or how you fixed it?

Best regards,
Nikolay
