### ISSUE TITLE
[Crash] Fatal signal 11 (SIGSEGV),

### ISSUE THREAD

**Issue by ali991** [opentok/opentok-android-sdk-samples#172]
When sending a signal from server using the opentok sdk : 
doc : https://www.npmjs.com/package/opentok#sending-signals
for example : 
`opentok.signal("SESSION_ID",undefined, { 'type': 'chat', 'data': 'Hello!' }, function(error) {
  if (error) return console.log("error:", error);
});`
; Android Client app (OpenTok v2.14.1) crashes resulting this error : 
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 10089

iOS Client receives these signals without any problem.

This crash is easily reproduced, just make sure to send signal event using opentok Node SDK or using directly REST API : https://api.opentok.com/v2/project/(API_KEY)/session/(SESSION_ID)/signal

**Comment by ali991** [comment]
this issue seems to be present only on SDK 2.14.+

**Comment by marinaserranomontes** [comment]
Hi @ali991 ,

Thanks to report it. We are going to take a look.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @ali991 ,

I’m closing this issue because it has been inactive for a few weeks. The fix for this issue will be included in the next SDK release.

You can also contribute directly to samples by providing a patch.

Thank you!

Best,
Marina

**Comment by sebandres** [comment]
I just ran into this exact issue yesterday. 

Version 2.15.3 works without issues but version 2.16.0 present this same crash. I'm assuming the bug was re-introduced on version 2.16.0.

Using Android 4.2.2 compiling to target android API 17.

Happy to provide any logs necessary.

I am using the `Basic-Video-Chat` example without any changes (other than updating the api keys).

**Comment by anmarbro** [comment]
Same happening on Android 5.1.1 API 22.
Working fine on version 2.15.3 but crashing on 2.16.0

**Comment by toni1727** [comment]
Same happening on Android 7.1.2 API 25.
Working fine on version 2.15.3 but crashing on 2.16.+
