### ISSUE TITLE
PublisherView disappear after resume

### ISSUE THREAD

**Issue by TooLazyy** [opentok/opentok-android-sdk-samples#174]
Hi. I'm using com.opentok.android:opentok-android-sdk:2.14.2.
After activity is resumed (back to activity from another one), publisher and subscribers streams are disappeared, sound not.
**Steps to reproduce:**
1 - Copy code from **Multiparty-ConstraintLayout** sample.
2 - Add 1 button, by click open a new activity with just an empty layout. Go back. Publisher view and subscriber view disappeared.
Tested on Xiaomi Mi 3W (6.0 android) and Meizu M1 Note (5.1 android).

A very similar [issue](https://github.com/opentok/opentok-android-sdk-samples/issues/130) exists.
But on my device `publisher.getView()` returns an instance of a `TextureView` (not a `GLSurfaceView`) where `setZOrderOnTop` method is not present.

Is there any way to resume video stream?

P.S. From the other side of the video call video stream is resuming after `onResume` is called, so it disappear only on the source side.

**#EDIT1**
Getting this only with a `TextureView` and `publisher.onPause()`, `publisher.onResume()`.
```
sessionOptions(new Session.SessionOptions() {
                    @Override
                    public boolean useTextureViews() {
                        return true;
                    }
                })
```

**Comment by marinaserranomontes** [comment]
Hi @TooLazyy ,

To fix the Z-Ordering, please take a look to this PR:
https://github.com/opentok/opentok-android-sdk-samples/pull/146

Basically you can fix it adding ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true); when using SurfaceViews.

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @TooLazyy  ,

I’m closing this issue because it has been inactive for a few weeks.
Please re-open if needed.

Thank you!

Best,
Marina

**Comment by kunalqss** [comment]
This is a life saver ! Thanks !

**Comment by ashishnagarro** [comment]
@marinaserranomontes I am facing this issue with TextureView , could you plz help me on this??

**Comment by harsha973** [comment]
> Hi @TooLazyy ,
> 
> To fix the Z-Ordering, please take a look to this PR:
> #146
> 
> Basically you can fix it adding ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true); when using SurfaceViews.
> 
> Best,
> Marina

Wow, this worked.

My publisher just goes blank (completely transparent) when subscriber disconnects and connects.  Thanks much
