### ISSUE TITLE
There are no samples for Live streaming in android . 

### ISSUE THREAD

**Issue by shakil807g** [opentok/opentok-android-sdk-samples#175]
how can i do  live streaming in android with tokbox with more than 3000 people ??

**Comment by robjperez** [comment]
I recommend you to read our documentation about broadcasting:

https://tokbox.com/developer/guides/broadcast/

Depending on the use case, you will consume the feed via RTMP. We don't have samples in this repo since consuming RTMP is out of the scope of the opentok android sdk.
