### ISSUE TITLE
Change AudioDeviceManager output issue

### ISSUE THREAD

**Issue by TooLazyy** [opentok/opentok-android-sdk-samples#176]
SDK version - 2.14.+
Steps to reproduce: 
1 - copy Multiparty-ConstraintLayout project
2 - add code to play some ringtone from handset

```
Uri path = Uri.parse("android.resource://" + getPackageName() + "/" + R.raw.busy);
            Ringtone r = RingtoneManager.getRingtone(getApplicationContext(), path);
            r.setStreamType(AudioManager.STREAM_VOICE_CALL);
            AudioManager m = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
            if (m != null) {
                m.setMode(AudioManager.MODE_IN_CALL);
                m.setSpeakerphoneOn(false);
            }
            r.play();
```
**After step 2 ringtone is playing from handset.**
3 - wait for `onStreamCreated` callback - sound becomes playing from **SpeakerPhone**

Setting `AudioDeviceManager.getAudioDevice()
.setOutputMode(BaseAudioDevice.OutputMode.Handset)` is not helping. Trying to set after `session.connect()`, after `onConnected()` callback, helps only after `onStreamCreated`, but sound plays for a second from SpeakerPhone.

What i expect - if i set output mode `BaseAudioDevice.OutputMode.Handset`, i expect sound to play always from `Handset` until `BaseAudioDevice.OutputMode.Handset` is set.

**Comment by marinaserranomontes** [comment]
HI @TooLazyy ,

Have you tried to set the OutputMode before to connect to the session? 
More info here: https://tokbox.com/developer/sdks/android/reference/com/opentok/android/BaseAudioDevice.html#setOutputMode-com.opentok.android.BaseAudioDevice.OutputMode-

Best,
Marina

**Comment by tokaaliamien** [comment]
I'm facing the same issue on com.opentok.android:opentok-android-sdk:2.18.1
Here's my code:
```
@AfterPermissionGranted(Constants.RC_AUDIO_PERM)
    private fun requestPermissions() {
        if (EasyPermissions.hasPermissions(this, *permissions)) {
            mSession = Session.Builder(this, API_KEY, SESSION_ID)
                .sessionOptions(object : Session.SessionOptions() {
                    override fun useTextureViews(): Boolean {
                        return true
                    }

                }).build()
            AudioDeviceManager.getAudioDevice().outputMode = BaseAudioDevice.OutputMode.Handset
            mSession?.setSessionListener(this)
            mSession?.connect(TOKEN_2)
        } else {
            EasyPermissions.requestPermissions(
                this,
                permissionMessage,
                requestCode,
                *permissions
            )
        }
    }
```
I also tried setting it in onStreamCreated method but it didn't do anything either!
I need to change the output device throughout the session too
