### ISSUE TITLE
 OpenTok Archiving Single Stream

### ISSUE THREAD

**Issue by shakil807g** [opentok/opentok-android-sdk-samples#177]
My use case is i'm using opentok video calling feature for broadcasting live stream where multiple user subscribe to a stream but only one can publish it .and i want to only archive only the publisher stream not other subscribers is it possible .

**Comment by marinaserranomontes** [comment]
Hi @shakil807g ,

To recorder the publisher stream, you have several options:

- You can use the MediaProjection API to record the screen.
- You can use the MediaRecorder, but please note, you don't need to use a CustomCapturer, you can setup the MediaRecorder in the Activity, and feed it with the input surfaces for the publisher.
- You can use MediaCodec to directly save the publisher video frames using a video encoder. In this case, you will need to build your own capturer in that case.

The last option seems to be the most difficult, so I recommend to you to try MediaProjection or MediaRecorder.

**Comment by shakil807g** [comment]
@marcioaffonso  Can i save the single stream to server with opentok archiving api  instead of storing locally ??

**Comment by marinaserranomontes** [comment]
@shakil807g  You could use the individual stream archiving option. 
https://tokbox.com/developer/guides/archiving/#individual-stream-and-composed-archives
