### ISSUE TITLE
Session is error. See the logcat please

### ISSUE THREAD

**Issue by hoangphu2390** [opentok/opentok-android-sdk-samples#179]
I'm using library "Custom Video Driver" to build livestream application include: 1 Publisher and multi Subcriber. I generate 2 tokens in my project on link website "https://tokbox.com". Inside will have 1 token for publisher and 1 token for subcriber .When running the application on two device, then device take role publisher work well, but device take role subcriber crashed, it show message "Session is error. See the logcat please" . 
Please check this bug on Android platform, I tested iOS platform with test case above, then it work well, Thanks!

![screenshot_20181005-123517_samsung experience home](https://user-images.githubusercontent.com/22810159/46517837-64b6fc80-c89b-11e8-96b2-9fa4310dbdd7.jpg)

**Comment by janoonaj** [comment]
What does logcat say?

**Comment by marinaserranomontes** [comment]
Hi @janoonaj ,

Sorry for the late reply. Please, could you share your logs from logcat? what is the Android SDK version you are using?

Best,
Marina

**Comment by janoonaj** [comment]
Hi @marinaserranomontes , I wanted to ask and help @hoangphu2390 as well.

**Comment by marinaserranomontes** [comment]
Thanks, @janoonaj!!
@hoangphu2390 please, could you  share your logs from logcat?

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @hoangphu2390 ,

I’m closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue. You can also contribute directly to samples by providing a patch.

Thank you!

Best,
Marina
