### ISSUE TITLE
Share SurfaceView

### ISSUE THREAD

**Issue by zabi90** [opentok/opentok-android-sdk-samples#180]
Hi,
Is there any way to publish SurfaceView on stream in Android?
Actually i want to share my game screen that is develop in unity and unity player render game in SurfaceView.

**Comment by marinaserranomontes** [comment]
Hi @zabi90 ,

Please, could you confirm what do you mean with "share surfaceView" ? Do you want to render the publisher/subscriber view on SurfaceView? Or do you want to publish the content of a SurfaceView? 

Best,
Marina

**Comment by marinaserranomontes** [comment]
Hi @zabi90,

I think you could try to create your own VideoCapturer to get a Bitmap representation of the content of your view, and then passing it in the buffer.

You can find an example of CustomVideoCapturer here: https://github.com/opentok/opentok-android-sdk-samples/blob/master/Custom-Video-Driver/CustomVideoDriverLib/src/main/java/com/example/tokbox/CustomVideoDriverLib/CustomVideoCapturer.java

Best,
Marina
