### ISSUE TITLE
onStreamCreated not called sometimes

### ISSUE THREAD

**Issue by CatsNipYummy** [opentok/opentok-android-sdk-samples#181]
While using the Android SDK, say 2 out of 5 times the onStreamCreated is not called when I initialize a call. onConnected is called though. 
Due to which either streams don't appear on each other's devices. This does not happen always. But it does not give me an error when this issue occur.

My code is almost identical to the documentation page:

`
    public class VideoCallController extends AController implements Session.SessionListener, 
    PublisherKit.PublisherListener, Session.ConnectionListener {

    private static final String TAG = "VideoCallController";
    private static final int RC_SETTINGS_SCREEN_PERM = 123;
    private static final int RC_VIDEO_APP_PERM = 124;
    private static final String PHONE_OWNER = "TickTalk";

    private Session mSession;
    private Publisher mPublisher;
    private Subscriber mSubscriber;

    public VideoCallController(MainActivity activity) {
        super(activity);
    }

    public void fetchSessionConnectionData() {
        RequestQueue reqQueue = Volley.newRequestQueue(mActivity);
        reqQueue.add(new JsonObjectRequest(Request.Method.GET,
                "https://<url>" + "/session",
                null, new Response.Listener<JSONObject>() {

            @Override
            public void onResponse(JSONObject response) {
                try {
                    API_KEY = response.getString("apiKey");
                    SESSION_ID = response.getString("sessionId");
                    TOKEN = response.getString("token");

                    Log.i(TAG, "API_KEY: " + API_KEY);
                    Log.i(TAG, "SESSION_ID: " + SESSION_ID);
                    Log.i(TAG, "TOKEN: " + TOKEN);

                    mSession = new Session.Builder(mActivity, API_KEY, SESSION_ID).build();
                    mSession.setSessionListener(VideoCallController.this);
                    mSession.connect(TOKEN);

                } catch (JSONException error) {
                    Log.e(TAG, "Web Service error: " + error.getMessage());
                }
            }
        }, error -> Log.e(TAG, "Web Service error: " + error.getMessage())));
    }

    @Override
    public void onStreamCreated(PublisherKit publisherKit, Stream stream) {
        Log.e(TAG, "Web Service Stream Created: ");
    }

    @Override
    public void onStreamDestroyed(PublisherKit publisherKit, Stream stream) {
        Log.e(TAG, "Web Service Destroyed: ");
    }

    @Override
    public void onError(PublisherKit publisherKit, OpentokError opentokError) {
        Log.e(TAG, "Web Service Error: " + opentokError.getMessage());
    }

    @Override
    public void onConnectionCreated(Session session, Connection connection) {
        Log.e(TAG, "Web Service Connection Created: ");
    }

    @Override
    public void onConnectionDestroyed(Session session, Connection connection) {
        Log.e(TAG, "Web Service Connection Destroyed: ");
    }

    @Override
    public void onConnected(Session session) {
        Log.e(TAG, "Web Service onConnected: ");

                mPublisher = new Publisher.Builder(mActivity).build();
        mPublisher.setPublishAudio(false);
        mPublisher.setPublisherListener(this);

        mActivity.getPublisherView().addView(mPublisher.getView());
        mSession.publish(mPublisher);
    }

    @Override
    public void onDisconnected(Session session) {
        Log.e(TAG, "Web Service Disconnected: ");
    }

    @Override
    public void onStreamReceived(Session session, Stream stream) {
        Log.i(TAG, "Stream Received");

        if (mSubscriber == null) {
            mSubscriber = new Subscriber.Builder(mActivity, stream).build();
            mSubscriber.setSubscribeToVideo(true);
            mSession.subscribe(mSubscriber);
            mActivity.getSubscriberView().addView(mSubscriber.getView());
        }
    }

    @Override
    public void onStreamDropped(Session session, Stream stream) {
        Log.i(TAG, "Stream Dropped");
        mSession.disconnect();
        mActivity.stopVideoConference();

        if (mSubscriber != null) {
            mSubscriber = null;
            mActivity.getPublisherView().removeAllViews();
            mActivity.getSubscriberView().removeAllViews();
        }
    }

    @Override
    public void onError(Session session, OpentokError opentokError) {
        Log.e(TAG, "Web Service Error: " + opentokError.getMessage());
    }

    @Override
    public void onDestroy() {

    }
}
`

**Comment by marinaserranomontes** [comment]
Hi @CatsNipYummy ,

Just to comment, onStreamCreated event is invoked when the publisher's stream is created.
If you publish and the onStreamCreated event is not received and you are subscribed to the listener, it should send an error. 
Please, could you verify the logcat? Also, if you want to debug your OpenTok session, you could use https://tokbox.com/developer/tools/inspector. 

Best,
Marina

**Comment by CatsNipYummy** [comment]
I was using a custom capture system which was causing this issue.
