### ISSUE TITLE
Unable to share screen with video in web view or with native videoview

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#185]
I am able to share everything except video view in web-view or native.
Could you please look into this?

**Comment by ashishnagarro** [comment]
Could you please look into this and update me.
I also have sent an email for the same.

**Comment by marinaserranomontes** [comment]
Hi @ashishnagarro ,

Yes, you can share anything you have in a View. You could use MediaProjection and use their frames to build a custom video capturer.

Please, take a look to this repo: [https://github.com/opentok/accelerator-core-android
]
It is a simple library which make easier the way to integrate OpenTok SDK to Android apps, and it contains a sample code for Screensharing using MediaProjection API.

Best,
Marina

**Comment by ashishnagarro** [comment]
Thanks @marinaserranomontes for your inputs.
I will look into it.

**Comment by ashishnagarro** [comment]
@marcioaffonso : Yes it is working now.
But here we are facing issue of video scaling, on client side it is showing multiple frame side by side.
Please see attached screenshot. i tried to to set scale to fit/fill but nothing worked.
<img width="344" alt="screen shot 2018-11-15 at 5 22 57 pm" src="https://user-images.githubusercontent.com/28433423/48551299-2598b400-e8fb-11e8-84e8-538d9f122374.png">

**Comment by danielCarlosCE** [comment]
Hi there! 

I basically have the same scenario but in my case, I don't want to share the whole screen, as it does with media capture, is it possible?  I'm using a Webview with hardware accelerated

**Comment by marinaserranomontes** [comment]
Hi @danielCarlosCE ,

I think you could custom the ScreenSharingCapturer with the CustomView you want to share.

Please, take a look to the following code:
https://github.com/opentok/accelerator-core-android/blob/ec0aeffb8a160c2b6731173b1da2931d26a56613/accelerator-core/src/main/java/com/tokbox/android/otsdkwrapper/screensharing/ScreenSharingCapturer.java#L83

Best,
Marina
