### ISSUE TITLE
Unable to publish video view in screen share app

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#186]
Hi,

I want to publish video view for screen share, but getting black screen.
Please let me know the way how i can resolve this issue .

Thanks
Ashish

**Comment by marinaserranomontes** [comment]
Hi @ashishnagarro ,

I think it is related to your issue: https://github.com/opentok/opentok-android-sdk-samples/issues/185
Please, could you confirm it? Thanks!

**Comment by marinaserranomontes** [comment]
Thanks @ashishnagarro. Let me close it.

Best,
Marina
