### ISSUE TITLE
Black views

### ISSUE THREAD

**Issue by kpoznak** [opentok/opentok-android-sdk-samples#187]
Hi, 

I am having the following issues with OpenTok for Android:

1. When the app enters in foreground all the views that supposed to display streams are gone - I can't see myself(publisher) anymore.

2. After removing a stream's view and re-adding it into another viewgroup the view is black. 

I am also using TextureViews instead of SurfaceView.

In both cases it seems like the stream has been stopped, any ideas why?

**Comment by marinaserranomontes** [comment]
Hi @kpoznak ,

Just to understand the scenario, please could you detail if you are trying to test 1publisher-1subscriber? What is the sequence flow, first publisher, then subscribing? Etc.

Thanks.

Best,
Marina

**Comment by kpoznak** [comment]
A manager which is responsible for video call logic triggers a fragment with 2 views - publisher's and subscriber's. The publisher's view is loaded first but it always should be on top of the subcriber's view. What is important here is that the publisher's view has to be circular , that's why I used TextureView. If I set setZOrderOnTop(true) the publisher's view would not respect the parent's shape. 

The fragment has an option to "minimize" itself which in reality means that the manager removes the fragment and adds a new layer on top of an activity  with subscriber's view. Unfortunately the re-added view is black. It only happens with TextureView.

**Comment by Anjula** [comment]
At the first time after app launch, I'm also getting a black screen (publisher). When retrying it won't happen.

**Comment by ashishnagarro** [comment]
Any update on this issue, I am also facing this issue.

**Comment by ashishnagarro** [comment]
@marinaserranomontes I am also facing same issue. Could you please help on this?

**Comment by bholendraofficial** [comment]
also i am facing same issue in android pie

**Comment by robjperez** [comment]
Going to close this as aged issue. Please reopen if necessary
