### ISSUE TITLE
Failed to resolve: com.opentok.android:opentok-android-sdk:2.15.1

### ISSUE THREAD

**Issue by milosgh** [opentok/opentok-android-sdk-samples#188]
Hi,

I'm having issues resolving the OpenTok SDK when I want to place it inside the module.
It works well if I put tokbox repo url under root build.gradle -> allprojects -> repositories:

> allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://tokbox.bintray.com/maven" }
    }
}

But I want to use your SDK like a dependency only within a module, and it should work if I put your repo inside module's build.gradle only:

> buildscript {
    repositories {
        maven { url "http://tokbox.bintray.com/maven" }
    }
}

Is it possible to do so?

Regards,
Milos

**Comment by marinaserranomontes** [comment]
Hi @milosgh ,

You could add it in the "build.gradle" file of the module:
Eg:
dependencies {
    repositories {
        maven { url 'https://maven.google.com' }
        maven { url 'http://tokbox.bintray.com/maven' }
    }
    compile fileTree(include: ['*.jar'], dir: 'libs')
   ....
}

**Comment by milosgh** [comment]
Hi,

Unfortunately putting it inside dependencies didn't work, but I managed to make it work inside a modules' build.gradle like this:

```
apply plugin: 'com.android.library'

rootProject.allprojects {
    repositories {
        maven { url 'https://tokbox.bintray.com/maven' }
    }
}
```
