### ISSUE TITLE
Android Activity com.Mobile has leaked IntentReceiver com.opentok.android.DefaultAudioDevice$1@95eae3e

### ISSUE THREAD

**Issue by coolwd10** [opentok/opentok-android-sdk-samples#189]
Android Activity com.Mobile has leaked IntentReceiver com.opentok.android.DefaultAudioDevice$1@95eae3e that was originally registered here. Are you missing a call to unregisterReceiver()? android.app.IntentReceiverLeaked: Activity com.Mobile has leaked IntentReceiver com.opentok.android.DefaultAudioDevice$1@95eae3e that was originally registered here. Are you missing a call to unregisterReceiver()? at android.app.LoadedApk$ReceiverDispatcher.(LoadedApk.java:1159)

I am calling servicce.onpuse and service.onresume But still facing the issue any boday can help me

**Comment by vishalvasani18** [comment]
I am also facing the same issue.

**Comment by robjperez** [comment]
This should be fixed in 2.17.0, please reopen this if it is still crashing.

**Comment by MartinLiva** [comment]
I'm experiencing the same thing in my app. I tried to clone the samples and the same is happening there.
It happens on screen rotation.

I've tried ```AudioDeviceManager.getAudioDevice().onPause()``` (which is suggested in another issue) and it didn't help.

I'm using version ```2.17.1```

Steps to reproduce:
1. Connecting to session
2. Rotate phone, resulting in
```Activity has leaked IntentReceiver com.opentok.android.DefaultAudioDevice$1@c9ae257```
The app does not crash at this point
3. Rotate back, resulting in
```Activity}: java.lang.IllegalArgumentException: Receiver not registered: com.opentok.android.DefaultAudioDevice$3@1ec17f1```
App crashes at this point
