### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6 in tid 30547 at  Session mSession = new Session.Builder(context, apiKey, sessionId).build();

### ISSUE THREAD

**Issue by rohit-sharma-92** [opentok/opentok-android-sdk-samples#196]
I'm getting crash with error: 
**Fatal signal 6 (SIGABRT), code -6 in tid 30547**
at :
**Session mSession = new Session.Builder(context, apiKey, sessionId).build();**
On android 8.0 Oreo devices.
I'm using latest version of Opentok sdk i.e. com.opentok.android:opentok-android-sdk:2.15.3
Tried previous versions also.

**Comment by msach22** [comment]
@rohit-sharma-92 Can you please confirm what the `context` variable is set to?
Have you tried running the [Basic-Video-Chat](https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Chat) sample app available in this repo?

**Comment by rohit-sharma-92** [comment]
The context is the Context of the activity in which I'm try to  create the session. And the tutorial you are talking about, I didn't tried it on the Oreo devices.

**Comment by msach22** [comment]
Thanks for clarifying. Could you please try out the sample application and let me know if it's still happening for you?

**Comment by msach22** [comment]
@rohit-sharma-92 Just checking in, could you please try out the [Basic-Video-Chat](https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Chat) and see if you can reproduce the issue there?

**Comment by robjperez** [comment]
Closing this as aged issue. Please reopen if necessary
