### ISSUE TITLE
AudioDevice can only be changed before initialization.

### ISSUE THREAD

**Issue by rMozes** [opentok/opentok-android-sdk-samples#200]
Hi Team,

I am getting this error AudioDevice can only be changed before initialization in 2.15.3. I previously used the version 2.14.3  and it worked fine there. As I see in the code, this error is thrown when the V3AudioDriver is active. The only thing I don't understand, why the V3AudioDriver is active. I already disconnected from the previous session and I try to create a new session with a custom audio device.
Could you please take a look at it?

**Comment by fjzboy** [comment]
Hi, I meet the same issue, do you have any method to fix it?

**Comment by rMozes** [comment]
@fjzboy, unfortunately, I don't have, I switched back to 2.14.3

**Comment by robjperez** [comment]
Hi!

I'm afraid that the AudioDevice cannot be changed after you use connect to a session of after building a publisher.

**Comment by mohdzaid2612** [comment]
I just resolved this issue by removing the line `enableStereoOutput: true`.

**Comment by Panda-ref** [comment]
For those coming here:
it will always crash if you have `isCamera2Capable: true` together with `enableStereoOutput: true`.
Setting `isCamera2Capable: false` allowed us to use this OT custom audio driver that handles audio routing in a much better way than the default one.
