### ISSUE TITLE
Subscriber/Publisher not resume on API 23 Android

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#203]
Hi,

I am using TextureView and when app is resumed all videos (publisher & subscriber) turns into black. Audio is available.

please suggest me what i should do. Should i use surface view with zOrderTop = 0 ?

When i use surface view with zOrderTop then it overlaps some UI component drawn above that RelativeLayoutContainer.

This error is only for API level 23 or below.

Waiting for reply.

Thanks
Ashish

**Comment by ashishnagarro** [comment]
Any update on this? Could you guys please check this issue.

**Comment by ashishnagarro** [comment]
Could you guys please help me on this issue?

**Comment by robjperez** [comment]
Is this still happening on 2.17 ?

Please reopen the ticket if it is still not working.
