### ISSUE TITLE
Native thread exiting without having called DetachCurrentThread

### ISSUE THREAD

**Issue by sohailniazai** [opentok/opentok-android-sdk-samples#204]
Hi, I upgraded OpenTok version from 2.14.0 to 2.15.3, after upgrading to latest version I started facing issue when stream is dropped by other user. In 2.14.0, when I receive onStreamDropped(), I use the following code to disconnect the user : 
`if (mSubscriber.getStream().equals(stream)) {
            mSubscriber.destroy();
            mSubscriber = null;
}`
and it is working fine. But since I have upgraded to 2.15.3 , calling "mSubscriber.getStream().equals(stream)" this line of code results in hanging the app and in logCat I see this warning : 
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?) 

Please look into this issue. Currently, I have rolled back to previous version.

**Comment by robjperez** [comment]
Hi!,

Thanks for reporting it.

This issue will be fixed in the upcoming 2.16 release that will be released soon (we don't have a date yet).

When 2.16 please test it again and if you see the problem happening again, reopen this ticket.

**Comment by shahalRahman** [comment]
App froze after ending call. In logcat i can see this warning.
W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[57,tid=2791,Native,Thread*=0x55974d2880,peer=0x12c75e20,"Thread-218"]

I'm using OpenTok 2.18.0.
