### ISSUE TITLE
TimeoutException: com.opentok.android.v3.Publisher.finalize

### ISSUE THREAD

**Issue by tapz** [opentok/opentok-android-sdk-samples#209]
Crashes all the time in the finalize method. Probably at some point after calling session.disconnect.

com.opentok.android:opentok-android-sdk:2.15.3

```
03-29 12:30:20.805 2657 2669 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
03-29 12:30:20.805 2657 2669 E AndroidRuntime: Process: myapp, PID: 2657
03-29 12:30:20.805 2657 2669 E AndroidRuntime: java.util.concurrent.TimeoutException: com.opentok.android.v3.Publisher.finalize() timed out after 60 seconds
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at com.opentok.android.v3.Publisher.finalizeNative(Native Method)
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at com.opentok.android.v3.Publisher.finalize(Publisher.java:523)
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at java.lang.Daemons$Daemon.run(Daemons.java:103)
03-29 12:30:20.805 2657 2669 E AndroidRuntime: at java.lang.Thread.run(Thread.java:764)
```

**Comment by tapz** [comment]
Doing something in the finalize method that can potentially cause a deadlock or timeout does not sound a very good idea to me.

**Comment by tapz** [comment]
My code that initializes the Publisher:

```
    Publisher publisher = new Publisher.Builder(getReactApplicationContext())
      .resolution(Publisher.CameraCaptureResolution.HIGH)
      .frameRate(Publisher.CameraCaptureFrameRate.FPS_30)
      .audioBitrate(64000)
      .build();

    publisher.setPublisherListener(this);
    publisher.getRenderer().setStyle(
      BaseVideoRenderer.STYLE_VIDEO_SCALE, 
      BaseVideoRenderer.STYLE_VIDEO_FILL);
    publisher.setPublishVideo(true);
    publisher.getView().setEnabled(true);
    publisher.getView().setVisibility(View.VISIBLE);

    if (publisher.getView() instanceof GLSurfaceView) {
      ((GLSurfaceView) publisher.getView()).setZOrderOnTop(true);
    }

    session.publish(publisher);
    ...
    publisher.getView().setOnTouchListener(new View.OnTouchListener() { … }
```

**Comment by tapz** [comment]
When running under debugger and the thread creating a new session freezes the stack traces show the following. For me this looks like a deadlock between the finalizer of the previous session and init of a new session.

"mqt_native_modules@14371" prio=5 tid=0xb96f nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.opentok.android.v3.Session.initNative(Session.java:-1)
	  at com.opentok.android.v3.Session.<init>(Session.java:517)
	  at com.opentok.android.v3.Session$Builder.build(Session.java:249)
	  at com.opentok.android.Session.<init>(Session.java:734)
	  at com.opentok.android.Session$Builder.build(Session.java:602)

"FinalizerDaemon@16935" daemon prio=5 tid=0xb918 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.opentok.android.v3.Publisher.finalizeNative(Publisher.java:-1)
	  at com.opentok.android.v3.Publisher.finalize(Publisher.java:523)
	  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
	  at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
	  at java.lang.Daemons$Daemon.run(Daemons.java:103)
	  at java.lang.Thread.run(Thread.java:764)

**Comment by tapz** [comment]
`Session session = new Session.Builder(this.reactContext, apiKey, sessionId).build();`

**Comment by tapz** [comment]
I tested keeping the old Publisher object references in a list. Now freezing and finalizer timeout anymore. Probably have to add somekind of hack to release the references and call System.gc in the middle of the night. Probably also restart the process just for sure.

**Comment by tapz** [comment]
I added publisher.destroy() and subscriber.destroy() and the finalize does not timeout anymore. Looks like the destroy method does the same thing as finalize, but synchronously in the same thread not in the background in the Android finalizer thread.

**Comment by robjperez** [comment]
This should be fixed in 2.17.0, please reopen this if it is still crashing.

**Comment by tapz** [comment]
2.17.0 removed the destroy methods. Without them the new version crashes as well.

**Comment by robjperez** [comment]
In 2.17 you don't need to manually call destroy, the object will be destroyed by the GC.

Can you describe the steps you are following to reproduce the crash?
Does it happen in Basic Video Chat?
