### ISSUE TITLE
Black publisher screen with PiP sample

### ISSUE THREAD

**Issue by Gryzor** [opentok/opentok-android-sdk-samples#210]
## Context
* Running the Picture-in-Picture sample (https://github.com/opentok/opentok-android-sdk-samples/tree/master/PictureInPicture) 
* Using the TokBox playground to create session/token(s), etc. 
* Nexus 5X / Android 8.1.0
* When Prompted, the Gradle/Gradle Plug-in was *not* updated to avoid differences with the sample.
* Android Studio:
```
Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-13-generic
```
* Server: The server is a trial instance of ToxBox; I tried two projects, one with VP8 Codec and one with H.264. Same results.

## Steps to Reproduce
Using the PiP Tokbox Sample App:

1. Update ApiKey, SessionID, and TokenID as usual
2. Launch app, give permissions, wait for your feed (and if there are subscribers, you should also see them).
3. With the app perfectly working (both publisher/subscriber are visible and transmitting both-ways), tap the PiP button.
4. App enters PiP ok. Observe you can still see/hear the subscriber's feed.
5. Tap the PiP window to go back to "full-screen".
6. PiP closes and the activity opens in full screen again.
7. Observe: Remote Feed still works, Publisher's screen is now "black"

## What is expected?
* My own feed (publisher) OpenGL view is properly restored and works after returning from PiP.

## What actually happens?
*  My own feed (publisher) is "black", no feed and no way to bring it back. 

## How about the samples?
* My initial reaction was to follow the OpenTok official [tutorials](https://tokbox.com/developer/tutorials/), more specifically both iOS and Android to build a sample from scratch to learn about the key pieces myself. I created a blank Android project (w/Kotlin) and didn't update Gradle to the new beta version (3.5.x), just left the version Android Studio set up for me. (note: for iOS, I created an Xcode project, used Cocoapods to get the framework and ran the basic-chat sample, I did *not* try PiP on iOS, but both apps -Android and iOS- were able to see/hear each other and so did the Web playground I used to test too).
* After I got those two 1:1 basic video/chat working (always using OpenTok's playground to create tokens/sessions), I took at look at the official samples and found/ran [the basic Video-Chat](https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Chat)  sample.
* Then I decided to try PiP and didn't initially see the PiP sample from ToK, so I took a look at what was needed in the official Google sample for PiP [repository](https://github.com/googlesamples/android-PictureInPicture).
* With some degree of success/failure, I searched and found [the picture-in-picture TokBox sample](https://github.com/opentok/opentok-android-sdk-samples/tree/master/PictureInPicture); this gave me some tips of things I wasn't doing the same way, so I updated my sample project and got it _working_ but with the bug I am describing here. 
* Then I decided to run the PiP sample "as-is" and here I am, reporting that it exhibits the same issue. 

### Screenshot(s)
<details>
<summary>Low quality GIF</summary>

![tpip](https://user-images.githubusercontent.com/15253/56914797-4de52b00-6ab5-11e9-87c5-d0550bbe0656.gif)

</details>

**Comment by Gryzor** [comment]
Additional Information: I ran this on a borrowed Samsung S10 and it appears that it works fine there. I have not been able to fix the issue on a Nexus 5X. I'll ask our Q.A. department to run the demo on a bunch of Android devices and see which ones work and which fail, maybe it's a Nexus 5X issue (which wouldn't surprise me)

**Comment by rperezcubero** [comment]
Going to close this due to inactivity. 

Please reopen if the sample is not working well.
