### ISSUE TITLE
WebRTC bundled with OpenTok artifact

### ISSUE THREAD

**Issue by sebastianmarschall** [opentok/opentok-android-sdk-samples#212]
is there any reason why the webrtc is bundled within the opentok artifact and not declared as dependency?
this leads to problems when used in combination with other libraries that depend on webrtc

thanks and kind regards

**Comment by robjperez** [comment]
Hi @sebastianmarschall 

The reason we don't use webrtc as a dependency is because we don't use vanilla webrtc, we use our custom build of webrtc so we need to bundle it alongside the sdk.

In any case, we take note of your comment in order to explore solutions to this kind of conflicts in future releases.

**Comment by sebastianmarschall** [comment]
hi @robjperez 
thanks for your response.
maybe, as a first step, you could change the packagename?

**Comment by kkbpower** [comment]
@sebastianmarschall 
I really curious too! I have same issue.

**Comment by jayarajm** [comment]
Yes, I'm also facing same issue.
When we can expect package name update?

@sebastianmarschall can you please reopen this issue?

**Comment by sebastianmarschall** [comment]
@jayarajm sorry i can't, since @robjperez closed it - not me

**Comment by jayarajm** [comment]
@sebastianmarschall Okay. Thanks.
I will create a new Issue. 
[https://github.com/opentok/opentok-android-sdk-samples/issues/250](url)

Also I like to know, Did you manage to integrate any other webrtc lib along with opentok?

**Comment by sebastianmarschall** [comment]
@jayarajm yeah, i unzipped the opentok aar file, deleted the webrtc.jar, zipped it again and added it to my projects libs folder.
