### ISSUE TITLE
Subscriber stream scale type = FIT flicker on some devices

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#214]
Hi,

When i subscribe stream (Sharing screen from JS) then stream is getting flickered on some devices. It doesn't depend upon OS version.

If i set scaling to FILL then it crops the content so my requirement is fulfil with FIT scale type.

Please look into it.

**Comment by robjperez** [comment]
Hi @ashishnagarro 

It should be fixed in 2.17, please reopen this if it still does not work well
