### ISSUE TITLE
In-app OpenTok subscribed audio becomes too quiet after an incoming phone call and audio control slider is now all the way up

### ISSUE THREAD

**Issue by frankkubista** [opentok/opentok-android-sdk-samples#218]
Using OpenTok Android SDK version 2.16.0

Current behavior:
OpenTok behavior is normal until an incoming phone call. After answering the phone call and coming back to the app or just letting it ring during an OpenTok session, OpenTok subscribed audio volume is drastically reduced and the user has no way of turning up the volume since the audio control slider is now all the way up even if it wasn't all the way up before the call.

Steps to reproduce:
Start an OpenTok session in an app on the phone, subscribing to audio and video (or just audio). Observe audio behaving normally.
During the OpenTok session, have someone call the phone from step 1 using another phone (normal phone call).
The user of the phone from step 1 should answer the call, and then hang up.
Observe that audio volume has reduced drastically and the audio control slider is now all the way up.

What is the expected correct behavior:
OpenTok subscriber audio and audio control slider should be back to pre-call volume after each phone call.

**Comment by rperezcubero** [comment]
I could not repro this with 2.18

Going to close the ticket since it is quite old. Please reopen if necessary.
