### ISSUE TITLE
How can I use opentok sdk and original webrtc sdk?

### ISSUE THREAD

**Issue by kkbpower** [opentok/opentok-android-sdk-samples#222]
I wanna use original webrtc sdk with Opentok sdk.

Opentok has webrtc classes. 
=> package name: "org.webrtc"
Webrtc sdk has webrtc classes.
=> package name: "org.webrtc"
I can't import same package libraries in my project.

So I tried to use only Opentok sdk.
Then when I needed original webrtc in source code, I tried to use webrtc package in Opentok.
But Opentok uses custom "libjingle_peerconnection_so.so" as "libopentok.so". So I faced exception about "fault addr".

How can I use Opentok sdk and original webrtc sdk? Please help me.

**Comment by DarthMech** [comment]
+1. 
I have same problem.

**Comment by kostyabakay** [comment]
Is there any solution to this issue?

**Comment by robjperez** [comment]
Hi @kostyabakay 
Please try 2.17 release. It should be possible now to mix webrtc and opentok.

**Comment by kostyabakay** [comment]
@robjperez thank you for this fix!

**Comment by robjperez** [comment]
@kostyabakay 

Happy to know that this is working for you. Going to close the issue then. Please reopen if you find any problem.
