### ISSUE TITLE
Use SpeechRecognizer during call

### ISSUE THREAD

**Issue by ArikMixin** [opentok/opentok-android-sdk-samples#229]
My app makes video / audio call  via TokBox, i need to use SpeechToText service (SpeechRecognizer) during the call.

From what I read, i can not use the device mic (stream) for two uses in the same time.

I tried to disable the call for a moment or mute the audio to fire the SpeechToText, but it is work only when i hang-up the call (Unpublished / Disconnect)

Thank you

**Comment by jintgeorge** [comment]
You can use the custom audio driver https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Audio-Driver to access the audio samples.

**Comment by ArikMixin** [comment]
Thank you, it's works,
 but now i can not get back to the TokBox audio stream.
Can you be more specific?

I am calling
> customAudioDevice.stopCapturer (); to use the SpeechToText service.
and when i'm want to come back to the Tokbox Audio stream

i'm calling
> customAudioDevice.startCapturer ();
method, but the audio stream not returning.

**Comment by jintgeorge** [comment]
Are you getting any error ?

**Comment by ArikMixin** [comment]
It has been taken care of, now everything works as expected.
thank you very much !
