### ISSUE TITLE
Incoming video call not launch when app in background or killed.

### ISSUE THREAD

**Issue by ashishsharma30** [opentok/opentok-android-sdk-samples#234]
Hi @tcondit, @deniskras, @robjperez, @willyaranda, @jaoo,

I've a issue with deploying in android, when my app is active it's (Video call) working properly.
But when my app in background or killed, my video call activity not launch.
I want functionality like whatsapp, I tried with broadcast receiver but it's not working.
can you suggest me how to deploy this type of functionality.

Thanks & Regards
Ashish

**Comment by robjperez** [comment]
Sorry, I'm not sure I understand the issue.

Going to close it as it was reported long time ago. Please reopen it if needed
