### ISSUE TITLE
How to increase frame  metadata size

### ISSUE THREAD

**Issue by madhaviKumari** [opentok/opentok-android-sdk-samples#240]
It is define in the documentation that frame metadata size should be upto 32 Bytes, Our requirement is to increase the meta data size, Is there any way to increase metadata size upto 100 bytes.?

**Comment by robjperez** [comment]
Hi!

Frame metadata is sent along video data packets so the size available is quite low. 
I'm afraid we cannot increase the size of the data.

Please consider some way to split the data in several frames or compress it somehow.

Hope it helps!
