### ISSUE TITLE
Publisher view is black android 9 samsung s9plus

### ISSUE THREAD

**Issue by surendrayalakala** [opentok/opentok-android-sdk-samples#245]
In my android application whenever publish the video I am getting the black screen and getting error java.lang.runtime exception set parameters failed. I am using CustomVideoCapturer class. please help me.

**Comment by robjperez** [comment]
Can you provide more details @surendrayalakala ?
Are you using the sample of this repo?
Have you done any modifications to it?

**Comment by sagar-nickelfox** [comment]
I'm also facing the same issue. Sometimes when I start publishing, session successfully connecting but the publisher camera preview gets black. And when I try to subscribe the same stream it shows the same black color on subscriber end. To make it work I have to kill the app and start publishing again.

**Comment by rperezcubero** [comment]
@sagar-nickelfox can you provide some more details?

How is your use case? Are you conecting, going back and connecting again to an opentok session?
Are you reusing the publisher?

Which version of the sdk are you using?

**Comment by rperezcubero** [comment]
Going to close this one. Please reopen if necessary.
