### ISSUE TITLE
connection callback 

### ISSUE THREAD

**Issue by Jonniu** [opentok/opentok-android-sdk-samples#246]
When entering the video for connection or video is in progress, network disconnection can not immediately get the network error connection callback. It took a long time to return 1022    @robjperez

**Comment by robjperez** [comment]
Hi,

Thanks for creating a ticket.

I'm afraid that I don't fully understand the problem you are facing.
Can you describe the steps you have following to get it?

**Comment by robjperez** [comment]
Going to close the ticket due to inactivity.
please reopen it if it is still bad.
