### ISSUE TITLE
NPE crash when Session.throwError is called

### ISSUE THREAD

**Issue by KaidoNinja** [opentok/opentok-android-sdk-samples#252]
In version 2.14.3, sessionListener!=null was checked before calling onError on int.

From version 2.15.0 this null check was done BEFORE posting a runnable to a handler, which would call onError. In fact, this null check should (also) be done before the actual call to onError.

So, before you could do something like this:
Session.unsubscribe(subscriber);
Session.setSessionListener(null);

But now this would lead to a NPE crash, because sessionListener.onError is run after setSessionListener(null).

Possible fix: Add a sessionListener!=null check before calling sessionListener.onError.

**Comment by robjperez** [comment]
Thanks for reporting it.

We will fix it in the next release.

**Comment by KaidoNinja** [comment]
Fixed in version 2.16.3, closing this issue.
