### ISSUE TITLE
couldn't find "libopentok.so", 64-bit support.

### ISSUE THREAD

**Issue by afsaredrisy** [opentok/opentok-android-sdk-samples#254]
Not able run sample application on 64-bit architecture phones. as earlier someone raise this issue since long back here is the link:  https://github.com/opentok/opentok-android-sdk-samples/issues/74.
Now android play store has made mandatory 64-bit architecture support. I am using sdk version 2.16.2. is it not 64 bit compliance? if not then what could be the work around to publish app on play-store.

**Comment by Alistair-Pawsquad** [comment]
Did you manage to resolve the 64 bit issue?
