### ISSUE TITLE
Phone call issue in 2.16.3

### ISSUE THREAD

**Issue by Arunkarthicknallasami** [opentok/opentok-android-sdk-samples#256]
When in a session if the user gets a call and if he attends it while coming back entire UI is freeze and no action can be done any further - OS - Android 10, Tokbox SDK 2.16.3

**Comment by shakil807g** [comment]
@Arunkarthicknallasami Have you found any solution?. Facing the same issue.

**Comment by robjperez** [comment]
This should be fixed on 2.17

Please reopen if it still crashes
