### ISSUE TITLE
How to disconnect user when application swipe to kill

### ISSUE THREAD

**Issue by chiragdabhi0007** [opentok/opentok-android-sdk-samples#257]
In group calling when i kill the application through this i can't disconnect the session and it reflect in other user screen that my view also showing in other user screen but it is stucked and next time i again connect to same session then my view is appearing twice in other user screen so how can i handle this same user view is showing twice.(one is freeze and other is working).

**Comment by PeraDev7** [comment]
In your manifest : 
```
<service
    android:name="com.myapp.MyService"
    android:stopWithTask="false" />
```

In the java activity : 
```
 public void onTaskRemoved(Intent rootIntent) {
//add the disconnect code.
}
```

**Comment by robjperez** [comment]
Thanks @PeraDev7 for posting the solution!
