### ISSUE TITLE
Android Tokbox Swaping video view according to user audio level

### ISSUE THREAD

**Issue by niravtopsy** [opentok/opentok-android-sdk-samples#259]
I am developing video call ( conference ) app, in that, i want to swap view based on user audio level, means if i have total 5 user in conference then who ever is speaking, that need to be in middle of view, means middle view swap with other view based on higher audio level. ( conference call is working fine but i just issue with swaping view )

My issue is,

In My xml having three row,

First row contain three subscribe view

Second row ( Middle and large ) contain publisher view

Third row contain two subscribe view.

Means total 5 subscriber and one middle publisher.

I set subscribe view as below :

    val container = findFirstEmptyContainer()
    if (container == null) {
        Toast.showLongToast(context, "New subscriber ignored. MAX_NUM_SUBSCRIBERS limit reached.")
        return
    }

    container.subscriber = subscriber
    container.container.addView(subscriber.view)
    container.txtName.text = name
    subscriber.setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FILL)
findFirstEmptyContainer() method used to fill view whatever is empty of of 5 view. currently i am adding view as in sequence of empty view.

For publisher,

     mPublisher = Publisher.Builder(this@VideoChatActivity).name(Prefs.getString(context, PrefsKey.BASIC_INFO_FIRST_NAME, "")).build()
     mPublisher?.setPublisherListener(this@VideoChatActivity)
     mPublisher?.setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FILL)
     publisherView?.addView(mPublisher?.view)
     mSession?.publish(mPublisher)
Now, i add setAudioLevelListener of both publisher and subscriber like below,

    mPublisher?.setAudioLevelListener(object : PublisherKit.AudioLevelListener {
            override fun onAudioLevelUpdated(p0: PublisherKit?, p1: Float) {

                publisherAudioLevel = p1.toDouble()

            }
        })
And,

    subscriber.setAudioLevelListener(object : SubscriberKit.AudioLevelListener {
        override fun onAudioLevelUpdated(p0: SubscriberKit?, p1: Float) {

            subscriberAudioLevel = p1.toDouble()
            subscriberViewShow = p0!!.stream    ( Adding stream of subscriber )
        }

    })
Now, i am comparing audio level of subscriber and publisher like below,

       if (subscriberViewShow != null) {
           if (subscriberAudioLevel > publisherAudioLevel) {
                val subscriberInn = Subscriber.Builder(this@VideoChatActivity, subscriberViewShow).build()

                publisherView.removeAllViews()
                publisherView?.addView(subscriberInn.view)
                mSession?.publish(mPublisher)
            }
        }
i am remove all publisher view and then add subscriber view like publisherView?.addView(subscriberInn.view) that is getting from the subscriber setAudioLevelListener ,

but after adding this view, my publisher view show black, So, I am stuck here, I get view and replace view with subscriber based on audio level, what going wrong here, if any one help here then it is very appreciated.

**Comment by igorwojda** [comment]
It looks like you are getting `publisherView` instance from SDK. You should always create some kind of container yourself (`ViewGroup`) and just add and/remove publisher/subscrber views to it (not mess with views provided by SDK) e.g:

```
myContainer.removeAllViews()
myContainer.addView(subscriberInn.view)
```

**Comment by igorwojda** [comment]
Have you been able to solve this problem?

**Comment by igorwojda** [comment]
I will close this. Feel free to reopen if needed.

**Comment by somanathbca** [comment]
i am also facing this same issue, i used my old object for subscriber not creating a new one but still getting black screen for some time like 4 to 5 sec and then it work perfectly,
some time view become black for forever can you please help me out 

  @Override
    public void onAudioLevelUpdated(SubscriberKit subscriberKit, float v) {
        if (!isScreenShareActive) {
            if (subscriberKit != null && subscriberKit.getSession() != null && subscriberKit.getSession().getSessionId() != null) {
                System.out.println("ConferenceActivity.onAudioLevelUpdated data " + v + " session id " + subscriberKit.getSession().getSessionId());
                if (!TokBoxConfig.isOneToOne) {
                    if (v > 0.2) {
                        if (mainViewSubscriberView != null && mainViewSubscriberView.subscriber != null) {
                            if (mainViewSubscriberView.subscriber.getStream().getStreamId().equalsIgnoreCase(subscriberKit.getStream().getStreamId())) {
                                return;
                            } else {
                                if (!issomeonetalking) {
                                    setVoiceview(subscriberKit.getStream().getStreamId());
                                }
                            }
                        } else {
                            if (!issomeonetalking) {
                                setVoiceview(subscriberKit.getStream().getStreamId());
                            }
                        }
                    }
                }
            }
        }
    }
    
    
    
    
        private void setVoiceview(String streamid) {
        if (TokBoxConfig.isAutofocusEnable) {
            if (!isgrid) {
                issomeonetalking = true;
                SubscriberContainer subscriberContainerobj = findContainerForStreamId(streamid);

                if (subscriberContainerobj.subscriber == null) {
                    System.out.println("ConferenceActivity.onClick this is null ");
                    return;
                } else {
                    System.out.println("ConferenceActivity.onClick session id " + subscriberContainerobj.subscriber.getSession().getSessionId());
                }
                if (mainViewSubscriberView != null && mainViewSubscriberView.subscriber != null) {
                    if (mainViewSubscriberView.subscriber.getStream().getStreamId().equalsIgnoreCase(streamid)) {
                        return;
                    }
                }
                SubscriberContainer subscriberContainer = getUserfromTag(mainViewSubscriberView.tag);
                emoticonsspk.setVisibility(View.GONE);
                subscriberviewmain.removeAllViews();
                if (subscriberContainer != null) {
                    subscriberContainer.mainview.setVisibility(View.VISIBLE);
                    subscriberContainer.isonmain = false;
                    subscriberContainer.container.addView(subscriberContainer.subscriber.getView());
                }


                if (subscriberContainerobj.subscriber != null) {
                    subscriberContainerobj.mainview.setVisibility(View.GONE);
                    subscriberContainerobj.container.removeAllViews();
                    subscriberContainerobj.isonmain = true;
                    mainViewSubscriberView = subscriberContainerobj;
                    subscriberviewmain.addView(mainViewSubscriberView.subscriber.getView());
                }
                setHoldonFlactuation();
            }
        }

    }
