### ISSUE TITLE
Not working On connection listner in android

### ISSUE THREAD

**Issue by chiragdabhi0007** [opentok/opentok-android-sdk-samples#260]
I want to get total live connection in current session so i am using below interface but this is not working..

mSession?.setConnectionListener(object :Session.ConnectionListener{
            override fun onConnectionDestroyed(p0: Session?, p1: Connection?) {
                totalConnection--
                println("Connected users:::" + totalConnection)
            }

            override fun onConnectionCreated(p0: Session?, p1: Connection?) {
                totalConnection++
               println("Connected users:::" + totalConnection)
            }
        })

**Comment by robjperez** [comment]
Hi @chiragdabhi0007 

Callbacks works as expected in the SDK. Problem might be anywhere else in your code.

Going to close the ticket. Please reopen it if you still are having the problem. 
Please specify SDK version you are using.
