### ISSUE TITLE
Is your SDK available in Kotlin ?

### ISSUE THREAD

**Issue by manishpatelgt** [opentok/opentok-android-sdk-samples#261]

**Comment by marinaserranomontes** [comment]
Hi @manishpatelgt ,

You can find a simple multiparty App using OpenTok Android SDK and developed using Kotlin 1.1.2 here: https://github.com/robjperez/opentok-testmultiparty
https://tokbox.com/blog/google-io-kotlin-android-will-simplify-user-experience-development/

Best,
Marina

**Comment by robjperez** [comment]
Hi!

Our sdk should be used from kotlin without any issues. Please if you find any problem don't hesitate to report it here!
