### ISSUE TITLE
Replace Camera with Camera2 in Custom Video Capturer

### ISSUE THREAD

**Issue by cemalaytekin** [opentok/opentok-android-sdk-samples#262]
The android sample for Custom Video Capturer is currently using Camera class which is deprecated in API 21. 

https://tokbox.com/blog/new-release-opentok-ios-android-2-9/

In this release, it says "now our default capturer uses Camera 2 API in supported devices, you can also enable Camera 2 API for the devices of your choice by using the new Session constructor which accepts a SessionOptions subclass."

Are there any example of Custom Video Capturer with Camera2 in sample? Or are there any on going development on this issue?  Thanks

**Comment by robjperez** [comment]
Hi!

We added it recently:

https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Capturer-Camera2

hope it helps!

**Comment by linking123** [comment]
> Hi!
> 
> We added it recently:
> 
> https://github.com/opentok/opentok-android-sdk-samples/tree/master/Custom-Capturer-Camera2
> 
> hope it helps!

@robjperez 404?
