### ISSUE TITLE
Video call is being crashed on samsung tab A on android pie 

### ISSUE THREAD

**Issue by dishantHealthkos** [opentok/opentok-android-sdk-samples#263]
When I am doing a video call to my application on Samsung tab A which is having android pie as an OS.
when do I click on accept the session started there and application get crashed? 
Eventually, there is no log generated for that crash, if there is somebody who can help me out do help.

**Comment by gangadhar1112** [comment]
Update sdk .

**Comment by robjperez** [comment]
Going to close this due to inactivity.

Please reopen if it still crashes on 2.17
