### ISSUE TITLE
Proguard settings

### ISSUE THREAD

**Issue by provJoshMieczkowski** [opentok/opentok-android-sdk-samples#268]
Hello, could you guys provide proguard settings that are not the super board ones below?

-keep class com.opentok.{ ; }
-keepclassmembers class com.opentok.{ ; }
-dontwarn com.opentok.**
-keep class org.webrtc.* { ; }

**Comment by robjperez** [comment]
In 2.17 they should look like this:

```
-keep class com.opentok.{ ; }
-keepclassmembers class com.opentok.{ ; }
-dontwarn com.opentok.**
-keep class org.otwebrtc.* { ; }
```

Hope it helps

**Comment by iori57** [comment]
it is 2.22.1 now and I need to add the below:
```
-keep class com.vonage.** { *; }
```
