### ISSUE TITLE
ANDROID_HW_AF_OBJECT_DISTANCD fail

### ISSUE THREAD

**Issue by PeraDev7** [opentok/opentok-android-sdk-samples#271]
Hello, when i start a session, the app crash after few seconds, and return to the previous activity.
In the log i can find this : 
///getAfObjectDistance get ANDROID_HW_AF_OBJECT_DISTANCD fail
///doSmartAEAlgo() failed to getSceneMode

Any feedback?
In the demo app all works perfectly

**Comment by PeraDev7** [comment]
Full log
[log.txt](https://github.com/opentok/opentok-android-sdk-samples/files/4493777/log.txt)

**Comment by robjperez** [comment]
@PeraDev7 can you try with 2.17?

I saw the logs and the exception does not seem to be opentok related.
Are you using custom audio device?

Will close the issue since it does not look opentok related, please reopen if it is still happening
