### ISSUE TITLE
/broadcast/layout 500 internal server error

### ISSUE THREAD

**Issue by designerprasan007** [opentok/opentok-android-sdk-samples#273]
hi. I'm trying to make work of layout for my tokbox project. and i found code and implemented too. everything is working fine.
now I have 3 layout methods each will call different layouts but when I make a post request to /broadcast/layout getting
an error as no active broadcast session found. first, I thought it's coz if I'm making a call without the broadcast so I made video broadcast
and then called layout but still got the same error. here below I'm attaching my server code and client code

call to /broadcast/layout

document.addEventListener('DOMContentLoaded', function () {
 document.getElementById('layout1').addEventListener('click', function (session) {
    alert("layout1");
    var updateBroadcastLayout = function (session) {
    http.post('/broadcast/layout', { streams: broadcast.streams, sessionId: session.sessionId,
     "layout": {
    "type": "bestFit",
  }
   }).then(function (result) { console.log(result); }).catch(function (error) { console.log(error); });
    };
  });
});

receiving the request and returning back to the client

router.post('/broadcast/layout', (req, res) => {
  const streams = R.path(['body', 'streams'], req);
  console.log(streams);
  console.log(tokboxsesionid);
  broadcast.updateLayout(streams, tokboxsesionid)
    .then(data => res.send(data))
    .catch(error => res.status(500).send(error));    
});

in tokboxsessionid i'm storing the session id from the /broadcast/start. in console,log(streams)
getting response as 1 and in console.log(tokboxsessionid) getting response of current sessionid.

please help me to come out this. thank you

**Comment by robjperez** [comment]
Hi!,

I'm sorry but this issue does not seem to be related with Android samples or the sdk.
Can you post this question in the support page? https://support.tokbox.com/hc/en-us

Thanks!
