### ISSUE TITLE
Is that possible to listen audio without adding mSubscriber?.view to ViewGroup ?

### ISSUE THREAD

**Issue by manishpatelgt** [opentok/opentok-android-sdk-samples#274]
I am checking is that possible to listen (subscriber) audio  without adding **mSubscriber?.view** to **ViewGroup** ?

I want to do this in background using service but service doesn't UI. So how to do this in background ?

 subscriber_container.addView(mSubscriber?.view)

**Comment by robjperez** [comment]
Hi @manishpatelgt 

Yes, it is possible to do so.

Audio is played when you do `session.subscribe(subscriberInstance)`

You don't need to add the subscriber view to any view to start listening audio.

Going to close the ticket, please reopen it if it does not work as expected.
