### ISSUE TITLE
can we fix bandwidth for publishers, make it wihtout adaptive streaming 

### ISSUE THREAD

**Issue by designerprasan007** [opentok/opentok-android-sdk-samples#275]
hi tokbox. as my title i want to fix the bandwidth for the publisher without making the adaptive. is this possible?

**Comment by robjperez** [comment]
Hi!

@designerprasan007 can you please be more specific?

I'm going to close the issue since this does not look like an issue nor the samples neither the SDK, however please let's continue the discussion in here
