### ISSUE TITLE
Black Publisher view after app goes from background android API 21-22

### ISSUE THREAD

**Issue by DzmitreyDanilau** [opentok/opentok-android-sdk-samples#279]
Faced this issue after updating android sdk to ver 2.17.0
Android API 21-22
When the app launch first it's ok.
But after app goes to background and than goes back, session retain successfully. Session start again, but publisher view (in mobile device is black), the same on the web side.
Problem disappears after reload application.

Samsung Galaxy s5, Nexus 4
It seems like VideoCaptor can't get access to Camera service.

By system:
CameraBase: An error occurred while connecting to camera: 1
OpenTokSdk:
In this case cammeraError() has been triggered.

**Comment by jaoo** [comment]
Hello! Thanks for filing this issue. We have been testing this and we cannot reproduce it. When the app resumes video capturing continues without any issue. I would be great if you share an sample app where the issue reproduces. Maybe you can use one of the samples in this repo. Thanks.

**Comment by DzmitreyDanilau** [comment]
The same issue
https://github.com/opentok/opentok-android-sdk-samples/issues/280
