### ISSUE TITLE
Updating from 2.16.6 to 2.17.0 error  - Android mobile

### ISSUE THREAD

**Issue by marcqtan** [opentok/opentok-android-sdk-samples#287]
Hello, when video calling, I only have black screen. It's working fine in 2.16.6.. but failing in 2.17.0
com.opentok.android:opentok-android-sdk:2.17.0

Error log below:

    # Fatal error in: ../../src/modules/utility/source/helpers_android.cc, line 74
    # last system error: 2
    # Check failed: !jni->ExceptionCheck()
    # Error during FindClass: org/otwebrtc/voiceengine/BuildInfo

06-05 18:54:22.560 28899-28899/com.osample W/System.err:     at com.opentok.android.Utils.init_otc_engine(Native Method)
06-05 18:54:22.560 28899-28899/com.osample W/System.err:     at com.opentok.android.Utils.initOtcEngine(Unknown Source)
06-05 18:54:22.560 28899-28899/com.osample W/System.err:     at com.opentok.android.Session.<init>(Unknown Source)
06-05 18:54:22.560 28899-28899/com.osample W/System.err:     at com.opentok.android.Session.<init>(Unknown Source)
06-05 18:54:22.560 28899-28899/com.osample W/System.err:     at com.opentok.android.Session.<init>(Unknown Source)

**Comment by robjperez** [comment]
hi @marcqtan 

Can you try to reproduce with BasicVideoChat from this repo?
Do you have any progruard rule that is removing classes from the final package?

**Comment by tush9011** [comment]
Add this in your proguaurd-rules.pro

#open tok
-keep class org.otwebrtc.** { *; }
-dontwarn com.opentok.*
-keep class com.opentok.** { *; }
-keepclassmembers class com.opentok.*{ *; }

**Comment by robjperez** [comment]
Closing this. Please reopen if the issue persists
