### ISSUE TITLE
Multiparty-ConstraintLayout issue

### ISSUE THREAD

**Issue by AmjedAli** [opentok/opentok-android-sdk-samples#289]
I am working with Multiparty-ConstraintLayout to display multiple layouts.But after the subscriber stream received, app shows full black screen.I just run your sample. here is the link of sample app [https://github.com/opentok/opentok-android-sdk-samples/tree/master/Multiparty-ConstraintLayout](url)

**Comment by mohanrajsk** [comment]
do u got solution for this? am also facing same issue..

**Comment by AmjedAli** [comment]
@mohanrajsk  not yet

**Comment by gismano** [comment]
I too facing this issue , anyone got solution

**Comment by AmjedAli** [comment]
@gismano You can create your own dynamics layouts .

**Comment by kamesh18** [comment]
This is because of constriant set change 0 to ConstraintSet.WRAP_CONTENT

`class ConstraintHelper(private val constraintSet: ConstraintSet = ConstraintSet(), private val container: Int) {

    fun layoutViewAboveView(aboveItemId: Int, belowItemId: Int) {
        constraintSet.constrainHeight(aboveItemId, ConstraintSet.WRAP_CONTENT)
        constraintSet.constrainHeight(belowItemId, ConstraintSet.WRAP_CONTENT)
        constraintSet.connect(aboveItemId, ConstraintSet.BOTTOM, belowItemId, ConstraintSet.TOP)
        constraintSet.connect(belowItemId, ConstraintSet.TOP, aboveItemId, ConstraintSet.BOTTOM)
    }

    fun layoutViewWithTopBound(viewId: Int, topBound: Int) {
        constraintSet.connect(viewId, ConstraintSet.TOP, topBound, ConstraintSet.TOP)
    }

    fun layoutViewWithBottomBound(viewId: Int, bottomBound: Int) {
        constraintSet.connect(viewId, ConstraintSet.BOTTOM, bottomBound, ConstraintSet.BOTTOM)
    }

    private fun layoutViewNextToView(leftViewId: Int, rightViewId: Int, leftBoundViewId: Int, rightBoundViewId: Int) {
        constraintSet.constrainWidth(leftViewId, ConstraintSet.WRAP_CONTENT)
        constraintSet.constrainWidth(rightViewId, ConstraintSet.WRAP_CONTENT)
        constraintSet.connect(leftViewId, ConstraintSet.LEFT, leftBoundViewId, ConstraintSet.LEFT)
        constraintSet.connect(leftViewId, ConstraintSet.RIGHT, rightViewId, ConstraintSet.LEFT)
        constraintSet.connect(rightViewId, ConstraintSet.RIGHT, rightBoundViewId, ConstraintSet.RIGHT)
        constraintSet.connect(rightViewId, ConstraintSet.LEFT, leftViewId, ConstraintSet.RIGHT)
    }

    private fun layoutViewOccupyingAllRow(viewId: Int, leftBoundViewId: Int, rightBoundViewId: Int) {
        constraintSet.constrainWidth(viewId, ConstraintSet.WRAP_CONTENT)
        constraintSet.connect(viewId, ConstraintSet.LEFT, leftBoundViewId, ConstraintSet.LEFT)
        constraintSet.connect(viewId, ConstraintSet.RIGHT, rightBoundViewId, ConstraintSet.RIGHT)
    }

    fun layoutTwoViewsOccupyingAllRow(leftViewId: Int, rightViewId: Int) {
        layoutViewNextToView(leftViewId, rightViewId, container, container)
    }

    fun layoutViewAllContainerWide(viewId: Int, containerId: Int) {
        layoutViewOccupyingAllRow(viewId, containerId, containerId)
    }

    fun applyToLayout(layout: ConstraintLayout, animated: Boolean) {
        if (animated) TransitionManager.beginDelayedTransition(layout)
        constraintSet.applyTo(layout)
    }

    fun layoutViewFullScreen(viewId: Int) {
        layoutViewAllContainerWide(viewId, container)
        layoutViewWithTopBound(viewId, container)
        layoutViewWithBottomBound(viewId, container)
    }
}
`

**Comment by rperezcubero** [comment]
The sample has been updated. Can you try with the new version of it?

**Comment by AmjedAli** [comment]
not yet but thanks for the update.
