### ISSUE TITLE
Getting crash in release mode in 2.17.0 and 2.17.1

### ISSUE THREAD

**Issue by sagar-nickelfox** [opentok/opentok-android-sdk-samples#293]
For versions upto 2.16.6, the proguard rules were working somehow. Found those rules in issue #178 .

Yesterday I've updated the version to 2.17.1. The app is getting crashed in release mode since then. 

Please provide the updated proguard rules for 2.17.1 .

**Comment by rperezcubero** [comment]
Please refer to this: https://github.com/opentok/opentok-android-sdk-samples/issues/268
