### ISSUE TITLE
PublisherKit onError not always called even when stream is not created

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-android-sdk-samples#295]
The following bug can be reproduced on the basic video chat. 

Sometimes (really rarely) my user do not get their stream published and no error is reported. I found a way to reproduce this bug systematically.

For this I use google meet. I create a meeting and activate screen sharing. Then I start the basic video chat and the stream is never published.
What is really disturbing is that you see your publisher miniature but the stream is not being sent to the other user in the chat

**Comment by enricop89** [comment]
@mbouxin I was able to reproduce it, we're going to investigate further. Thanks again for opening the issue!

**Comment by mbouxin** [comment]
👍 Thanks !

**Comment by t4ngth00** [comment]
Awesome :D!

**Comment by pardel** [comment]
Closing this as - please do reopen is still experiencing issues.
