### ISSUE TITLE
No client-side video on Android 7.0 

### ISSUE THREAD

**Issue by DanielGalarza** [opentok/opentok-android-sdk-samples#297]
Device: Nexus 6, Android 7.0

When starting a video session on a device running 7.0, I noticed that the client video isn't present in the session. We only see the video on the other end of the session. I would expect to see both the other end and smaller video of myself.

Expected:
You can see both the video on the other end and video from the device (captured on Samsung S8+, Android 9)
![device-2020-08-04-102149](https://user-images.githubusercontent.com/8992942/89318749-6e971b80-d63c-11ea-864e-2a0ab2d21fe5.png)

Actual:
You only see video from the other end (Nexus 6, Android 7.0)
![Screenshot_1596557548](https://user-images.githubusercontent.com/8992942/89318923-b0c05d00-d63c-11ea-8ad0-79a7e06844af.png)

**Comment by maheshordex** [comment]
@DanielGalarza 
Are you facing the same issue which I am facing have you got any resolution?
https://github.com/opentok/opentok-android-sdk-samples/issues/299

**Comment by DanielGalarza** [comment]
@maheshordex Yes, your issues seems really similar to mine. I haven't heard back from anyone on the opentok team yet 😞

**Comment by maheshordex** [comment]
@DanielGalarza 
I fixed this with code.
 
Add this code in
```
 @Override
 public void onConnected(Session session) {
        if (mPublisher.getView() instanceof GLSurfaceView) {
            ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true);
        }
  }
```

But now I have another issue many times I see a black screen instead of video. Do you have any idea why it shows black screen?

in onStreamReceived method many times I didn't get Stream. If I leave session and join again.

is there any way I can get list of all streams which connected in session?

**Comment by sureshmaidaragi1919** [comment]
Even I have faced the same issue, blank screen whenever new subscriber joins, only I can hear subscriber voice video is blank, even publisher video is also blank. What kind of sample is this?.

**Comment by maheshordex** [comment]
@sureshmaidaragi1919 any luck on black screen issue ?

**Comment by maheshordex** [comment]
@DanielGalarza 
is it working for you now ?

**Comment by sureshmaidaragi1919** [comment]
I tried this solution https://github.com/opentok/opentok-android-sdk-samples/issues/289 worked but the problem is not scaling properly here is the screenshot 
<img width="258" alt="Screenshot at Sep 04 09-08-45" src="https://user-images.githubusercontent.com/28126457/92197037-45151e00-ee8e-11ea-8d79-6af8ba23e67e.png">

**Comment by maheshordex** [comment]
@sureshmaidaragi1919 
Not sure but I think the issue in the layout.
You can simply set background color where you load video and check height and width cover by color which you set in the background.

**Comment by gireesh-gks** [comment]
@sureshmaidaragi1919  Update constraint layout to  "implementation 'androidx.constraintlayout:constraintlayout:2.0.1'"
![WhatsApp Image 2020-09-04 at 12 33 13 PM](https://user-images.githubusercontent.com/46922758/92209594-e4e0a500-eeaa-11ea-9252-847241c5292a.jpeg)

**Comment by maheshordex** [comment]
@sureshmaidaragi1919 
Where is the video ?

**Comment by sureshmaidaragi1919** [comment]
@gireesh-gks  I tried your solution too still issue is same

**Comment by gireesh-gks** [comment]
@sureshmaidaragi1919  Did u change anything in ConstraintHelper class ?

**Comment by sureshmaidaragi1919** [comment]
Can you upload your sample app code here @gireesh-gks, So that I can check

**Comment by gireesh-gks** [comment]
@sureshmaidaragi1919 

https://drive.google.com/file/d/1uPh3yzdWYjGJk3Doik8Qw9py7oE3zN5f/view?usp=sharing

Try this. This code is working for me. I already shared the screenshot of this

**Comment by DanielGalarza** [comment]
> Hi,
> 
> The problem could be what @maheshordex is pointing out.
> 
> Depending on how is your code, you could be laying out the publisher's view above the subscriber's and that's why you cannot see it.
> 
> You can fix it calling manually
> 
> ```
> if (mPublisher.getView() instanceof GLSurfaceView) {
>             ((GLSurfaceView) mPublisher.getView()).setZOrderOnTop(true);
> }
> ```

This worked for me! Thank you!
