### ISSUE TITLE
[OPENTOK-42903] Audio is broken after the second call

### ISSUE THREAD

**Issue by NataliiaZarudna** [opentok/opentok-android-sdk-samples#307]
Hi. After upgrade to 2.18.0 issue with sound on Android 5 described in https://github.com/opentok/opentok-android-sdk-samples/issues/280#issuecomment-626715698 is still there. Could you please double check?

TC:
1. Start a call between Android 10 (Pixel) and Android 5 (Moto G)

AR=ER. Audio is ok for both devices

3. Stop a call
4. Start another call with same devices

AR: on Android 5 sound is very laggy, with echos. Samehappened for Android 10.

**Comment by shahalRahman** [comment]
Happening with new SDK 2.18.1 as well.

**Comment by NataliiaZarudna** [comment]
Hello.
Checked the same issue on version 2.19.0 and issue is still there. 

Please check the audio records we've made for both sides of a call: 
https://user-images.githubusercontent.com/64954706/109664459-d16e7800-7b75-11eb-96e8-bd43b539f751.mp4
https://user-images.githubusercontent.com/64954706/109664462-d2070e80-7b75-11eb-9eb7-22a8d5b4944f.mp4.

**Reproduced on devices:**
Pixel 2 - Android 11
Sambung Galaxy Tab A (SM-T510) - Android 10
Samsung Galaxy Note 10 Lite (SM-N770F/DS) - Android 11.

**Comment by NataliiaZarudna** [comment]
We've found out that issue happens only with Pixel 2 (at least on other devices we have it works). On Pixel 2 during second call you cannot properly here other side.

Could you please advise what might be the cause or maybe you can think of some work around? Thank you!

**Comment by amanXcell** [comment]
Hello all, does anyone have the the solution for this issue as I am facing this issue in Android 8 currently.
