### ISSUE TITLE
Duplicate class a.a.a.a.a.a found in modules classes.jar

### ISSUE THREAD

**Issue by romanpozd-tg17** [opentok/opentok-android-sdk-samples#308]
Hey! 
We're using both openTok-android and stripe libraries in our project and after an attempt to update opentok version to 2.18.0 today we've got:
`  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class a.a.a.a.a.a found in modules classes.jar (com.opentok.android:opentok-android-sdk:2.18.0) and classes.jar (com.stripe:stripe-3ds2-android:4.0.5)
`

Worked great on previous version in our project - 2.15.3
Any ideas how to solve it? 
Thanks.

**Comment by robjperez** [comment]
Hi!, Looks like a proguard issue.

Take a look to this issue to see if it helps: https://github.com/opentok/opentok-android-sdk-samples/issues/268

**Comment by romanpozd-tg17** [comment]
> Hi!, Looks like a proguard issue.
> 
> Take a look to this issue to see if it helps: #268

Unfortunately didn't work for me.

**Comment by igorwojda** [comment]
I was able to reproduce this issue with these versions of dependencies:

```
implementation "com.opentok.android:opentok-android-sdk:2.18.0"
implementation "com.stripe:stripe-3ds2-android:4.0.5"
```

Boosting dependency versions to solved the problem for me:
```
implementation "com.opentok.android:opentok-android-sdk:2.18.1"
implementation "com.stripe:stripe-3ds2-android:5.0.1"
```

Feel free to reopen this issue if you still experience this problem
