### ISSUE TITLE
Problem with publishing audio in background on Android 9 and 10

### ISSUE THREAD

**Issue by tokaaliamien** [opentok/opentok-android-sdk-samples#309]
I'm using opentok to publish and subscribe to audio and video, but there's an issue with android 9 and 10 in publishing audio after putting the application in the backgound for awhile, it stops working although I can still other audio publishers.

Testing on Huawei ANE-LX1 (P20 lite) with android 9 
Opentok version 2.16.5

**Comment by adrienrx** [comment]
Hello @tokaaliamien ; I see you're using 2.16.5, have you tried the latest version of the SDK 2.18.0 ?

**Comment by pardel** [comment]
Closing as outdated.
