### ISSUE TITLE
Publisher.cyclecamera() not working properly.

### ISSUE THREAD

**Issue by maheshordex** [opentok/opentok-android-sdk-samples#310]
When I use this method the first time it slightly zooms publisher camera but not switch to the back camera.
When second time call this method it will be the switch from front to back
Every time I need to call this method twice.

**Comment by robjperez** [comment]
Hi @maheshordex 
thanks for the issue.

Which device are you using?

**Comment by maheshordex** [comment]
@robjperez 
Pixel 3a and Samsung A50
Android: 10 OS

**Comment by maheshordex** [comment]
@robjperez 
Any update on this ?

**Comment by v-kpheng** [comment]
@maheshordex, sorry for the belated reply.

This isn't a bug.  The Pixel 3a has several front-facing cameras, some of which appear similar.  To confirm, please open https://codepen.io/v-kpheng/pen/oNLbZmp?editors=0012 from your test device.  It'll log to the Console window what video devices are present on your test device (e.g., your Pixel 3a).

`cycleCamera` iterates through all enumerable video devices as expected.

**Comment by v-kpheng** [comment]
Closing, since this isn't a bug.
