### ISSUE TITLE
Error : Camera Failed and Error code:  3010

### ISSUE THREAD

**Issue by ankitgupta394** [opentok/opentok-android-sdk-samples#311]
I am not able to connect with tokbox session. It was working fine before 5 days. I am also sending my error code screen shot:

![error for opentok](https://user-images.githubusercontent.com/17039214/94152613-69668800-fe99-11ea-9a97-3566eba94665.png)

**Comment by ankitgupta394** [comment]
Some time we faced Cannot publish error. I am also sending screen shot for same.
![error for opentok2](https://user-images.githubusercontent.com/17039214/94230629-01a75000-ff20-11ea-9b15-261ea2f98279.png)

Could you please tell some solution basically we are facing this issue on production app

**Comment by igorwojda** [comment]
Can you please verify this with opentok SDK `2.18.1`? 
If the problem persists, please provide a sample project or code.

**Comment by igorwojda** [comment]
It's have been a while, so I will close this issue for now. Feel free to reopen it if you still need help on this.
