### ISSUE TITLE
Subscribers views not scaling 

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [opentok/opentok-android-sdk-samples#312]
<img width="202" alt="Screenshot at Sep 30 13-20-44" src="https://user-images.githubusercontent.com/28126457/94657929-c8a41c80-031f-11eb-9dc9-fd9b6f388c79.png">
 
As you can see two subscribers comes, there is a  **very big gap** (Highligheted in red color) between the publisher & subscribers can someone help to fix this

**Comment by adrienrx** [comment]
subscriber.getRenderer().setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FILL);

**Comment by pardel** [comment]
@sureshmaidaragi1919 Hope @adrienrx's solution worked for you. Will close this for now. Feel free to reopen if still experiencing issues.
