### ISSUE TITLE
[OPENTOK-42794] Video is freezing when Live Photo Capture is implemented in Group Video Call

### ISSUE THREAD

**Issue by AmrutBiz4** [opentok/opentok-android-sdk-samples#316]
Hello There,

I have implemented group video call using below sample code link -
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Simple-Multiparty

Also, I have additionally implemented live photo capture feature from below link on the publisher side -
https://github.com/opentok/opentok-android-sdk-samples/tree/master/Live-Photo-Capture

When live photo capture is implemented it is causing video freezing issues for all the
subscribers. But when I remove the live photo capture implementation (no custom renderer), the video freezing issue
is not appearing. I'm facing this issue with Android SDK version 2.17.1

So far what I have understood is that, the BasicCustomVideoRenderer is causing the video at the subscriber side to freeze.
This implementation seems to be very old. It was working fine when I used it with the Android SDK version 2.14.0
I searched for some different solutions as well but they all didn't work with opentok.

Please provide some solution on this so I can capture live photos as well as video doesn't freeze for
the subscribers. I will be waiting for your earliest feedback.

Thank you in advance.
Amrut Bidri

**Comment by igorwojda** [comment]
It looks like `Live-Photo-Capture` sample is broken by itself.
It freezes the video after a while (launch the app and do nothig).

**Comment by igorwojda** [comment]
It looks like we have a regression bug here. This bug relates to the sample projects (`Basic-Video-Renderer`, `Live-Photo-Capture`) or renderers in general, but his was working before:

```
// 2.14 = OK
// 2.15 = OK
// 2.16 = OK
// 2.17 = FREEZING
// 2.18 = FREEZING
```

**Comment by igorwojda** [comment]
It looks like there we had a bug in our samples. You need to add one simple fix.

The frame that the sdk sends to the Renderer in the `onFrame` method is now the property of the Renderer. It is up to this class to destroy the frame when it is not needed anymore:


```java
public void displayFrame(Frame frame) {
    frameLock.lock();
    if (currentFrame != null) {
        currentFrame.destroy(); // Disposes previous frame
    }
    currentFrame = frame;
    frameLock.unlock();
}
```

This PR will fix the problem in samples https://github.com/opentok/opentok-android-sdk-samples/pull/375/files
