### ISSUE TITLE
Unable to use camera toggle

### ISSUE THREAD

**Issue by AarthiRajarajan** [opentok/opentok-android-sdk-samples#321]
hi,

when integrate iframe with android app,unable to use camera toggle . camera is not  showing 
![device-2020-11-23-121155](https://user-images.githubusercontent.com/55425574/99934832-23d51700-2d85-11eb-80c4-a431213598bf.png)
when switch from camera toggle off to camera toggle on .

**Comment by igorwojda** [comment]
Can you please provide a sample project?

**Comment by igorwojda** [comment]
It's have been a while, so I will close this issue for now. Feel free to reopen it if you still need help on this.
