### ISSUE TITLE
popup camera not getting closed in oneplus 7

### ISSUE THREAD

**Issue by abhinay100** [opentok/opentok-android-sdk-samples#322]
Popup camera not getting closed automatically in one plus 7 and other popup cameras after stopping the call.Please let me know how to handle this scenario in vonage

**Comment by igorwojda** [comment]
Can you please be more specific on how to reproduce this issue? 
Please provide a sample project or code snippet.

**Comment by igorwojda** [comment]
It's have been a while, so I will close this issue for now. Feel free to reopen it if you still need help on this.
