### ISSUE TITLE
how to set unique id to publisher

### ISSUE THREAD

**Issue by keval02** [opentok/opentok-android-sdk-samples#325]
Using which property, I can set the unique id to the publisher when he starts the video. I want to get that unique id in other mobile so that I can display that particular video there.

**Comment by igorwojda** [comment]
To split various users/devices into separate sessions (separate video calls/conversations) you should create an opentok `session` and then when the user wants to join the session (on the mobile) you should retrieve the session token from your server.

If you want to send more data between session participants you can use Signaling ([Docs](https://tokbox.com/developer/guides/signaling/android/), [Sample](https://github.com/opentok/opentok-android-sdk-samples/tree/master/Signaling))

**Comment by igorwojda** [comment]
It's have been a while, so I will close this issue for now. Feel free to reopen it if you still need help on this. As an alternative, you can reach us at [Vonage Developer Community Slack](https://developer.nexmo.com/community/slack).
