### ISSUE TITLE
Session.Builder, Activity context or Android Application context?

### ISSUE THREAD

**Issue by adrienrx** [opentok/opentok-android-sdk-samples#353]
https://github.com/opentok/opentok-android-sdk-samples/blob/926c92eaa83d46c8596839f4f430f25022767c0c/Basic-Video-Chat/app/src/main/java/com/tokbox/sample/basicvideochat/MainActivity.java#L176

![image](https://user-images.githubusercontent.com/4056555/106159440-140ef000-6185-11eb-914d-06290f24c019.png)

Documentation isn't aligned with this sample. Even the code sample on the documentation pass this, which I assume is an Activity context, however the line bellow states "The Android application context associated with this process". 

So... What's the best practice? I would say the application context right ? To avoid memory leaks

**Comment by igorwojda** [comment]
This is WIP  - it will be addressed in few days

**Comment by igorwojda** [comment]
The context you used depends on the specific use case, but usually, it is desired for the session to live outside of the Activity e.g: live between activities. For production applications, it's convenient to use application context instead of activity context.

BTW docs will be updated soon.
