### ISSUE TITLE
Is opentok has supported USB camera ? 

### ISSUE THREAD

**Issue by gagansinghsohal** [opentok/opentok-android-sdk-samples#358]

**Comment by igorwojda** [comment]
It should be possible.

1. The Android platform supports the use of plug-and-play USB cameras (that is, webcams) using the standard Android Camera2 API: https://source.android.com/devices/camera/external-usb-cameras

2. We have this OT sample that uses Camera2 API as a source for video stream https://github.com/opentok/opentok-android-sdk-samples/tree/master/Basic-Video-Capturer-Camera-2

**Comment by igorwojda** [comment]
I will close this for now. 
Feel free to reopen if you have any more questions.
