### ISSUE TITLE
ClassNotFoundException on release mode

### ISSUE THREAD

**Issue by bilalsammour** [opentok/opentok-android-sdk-samples#382]
Hi there.

The app exits when opening the video call on release mode only.

I have investigated then found where the issue is, I have found the issues, the issue is: No pending exception expected: java.lang.ClassNotFoundException: com.opentok.android.SubscriberKit$SubscriberAudioStats.

I have attached the full error message as a text file, and screenshot as well.

Please advise.

![TokBox error](https://user-images.githubusercontent.com/1741316/116301349-9d47ba00-a7a8-11eb-897b-da0aa5602029.png)
[TokBox error.txt](https://github.com/opentok/opentok-android-sdk-samples/files/6387157/TokBox.error.txt)

**Comment by supriyaBharti15** [comment]
Hi,
I also having the same issue with release build. App is crashing while starting audio or video call. Development build its not crashing. Please suggest the solution for this.
![image](https://user-images.githubusercontent.com/49556276/118958161-c8c05d80-b97e-11eb-8f30-450641a975d9.png)

**Comment by supriyaBharti15** [comment]
> Hi there.
> 
> The app exits when opening the video call on release mode only.
> 
> I have investigated then found where the issue is, I have found the issues, the issue is: No pending exception expected: java.lang.ClassNotFoundException: com.opentok.android.SubscriberKit$SubscriberAudioStats.
> 
> I have attached the full error message as a text file, and screenshot as well.
> 
> Please advise.
> 
> ![TokBox error](https://user-images.githubusercontent.com/1741316/116301349-9d47ba00-a7a8-11eb-897b-da0aa5602029.png)
> [TokBox error.txt](https://github.com/opentok/opentok-android-sdk-samples/files/6387157/TokBox.error.txt)


Hi bilalsammour,
Just add below code to you proguard-rule file of your project. Its fixed crash in my kotlin project.

# opentok
-keep class com.opentok.android.v3.** { *; }
-keep class com.opentok.android.v3.$ { *; }
-keep public class * extends com.opentok.android.v3.OpentokException
-keep class com.opentok.android.** { *; }
-keep class com.opentok.android.Session { *; }
-keep class com.opentok.client.** { *; }
-keep class com.opentok.impl.** { *; }
-keep class com.opentok.otc.** { *; }
-keep class org.webrtc.** { *; }
-keep class org.otwebrtc.** { *; }
-keep class org.otwebrtc.voiceengine.** { *; }
-keep class org.otwebrtc.WebRtcClassLoader {*;}
-keep class org.otwebrtc.voiceengine61.** { *; }
-keep class org.otwebrtc.voiceengine.BuildInfo { *; }

-dontwarn com.opentok.**
-keepclassmembers class com.opentok.** { *; }

**Comment by bilalsammour** [comment]
> Hi,
> I also having the same issue with release build. App is crashing while starting audio or video call. Development build its not crashing. Please suggest the solution for this.
> ![image](https://user-images.githubusercontent.com/49556276/118958161-c8c05d80-b97e-11eb-8f30-450641a975d9.png)

I found a workaround to fix the issue:
* Open app build.gradle.
* Under buildTypes then release, add the following at the end:
            
```
minifyEnabled false
shrinkResources false

useProguard true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```
* Create proguard-rules.pro file to be in the same folder with build.gradle.
* In the created file add the following line:

`-keep class androidx.lifecycle.DefaultLifecycleObserver`

That is it.

**Comment by emartynov** [comment]
Do you guys consider to have example with the obfuscation rules?
Do you guys consider to ship with obfuscation rules inside aar file?

**Comment by izbari** [comment]
> > Hi there.
> > The app exits when opening the video call on release mode only.
> > I have investigated then found where the issue is, I have found the issues, the issue is: No pending exception expected: java.lang.ClassNotFoundException: com.opentok.android.SubscriberKit$SubscriberAudioStats.
> > I have attached the full error message as a text file, and screenshot as well.
> > Please advise.
> > ![TokBox error](https://user-images.githubusercontent.com/1741316/116301349-9d47ba00-a7a8-11eb-897b-da0aa5602029.png)
> > [TokBox error.txt](https://github.com/opentok/opentok-android-sdk-samples/files/6387157/TokBox.error.txt)
> 
> Hi bilalsammour, Just add below code to you proguard-rule file of your project. Its fixed crash in my kotlin project.
> # opentok
> 
> -keep class com.opentok.android.v3.** { _; } -keep class com.opentok.android.v3.$ { _; } -keep public class * extends com.opentok.android.v3.OpentokException -keep class com.opentok.android.__ { _; } -keep class com.opentok.android.Session { _; } -keep class com.opentok.client.__ { _; } -keep class com.opentok.impl._* { _; } -keep class com.opentok.otc._* { _; } -keep class org.webrtc._* { _; } -keep class org.otwebrtc._* { _; } -keep class org.otwebrtc.voiceengine._* { _; } -keep class org.otwebrtc.WebRtcClassLoader {_;} -keep class org.otwebrtc.voiceengine61.** { *; } -keep class org.otwebrtc.voiceengine.BuildInfo { *; }
> 
> -dontwarn com.opentok.** -keepclassmembers class com.opentok.** { *; }

i getting error like this
### 
![image](https://user-images.githubusercontent.com/73957984/185106589-ee956324-4102-4fd3-bad6-d3012a4ac22b.png)

**Comment by CamiiloAF** [comment]
useProguard was removed in gradle 7.0.0. If you're using gradle >7.0.0 just add the following lines under buildTypes :

`minifyEnabled false`
`shrinkResources false`
