### ISSUE TITLE
Android devices too much heating issue

### ISSUE THREAD

**Issue by nikul014** [opentok/opentok-android-sdk-samples#389]
Multiparty video calls up to 4 subscribers are giving heating issues after 10-15 minutes. Same result in pixel 4a and One Plus 8T. It was serious issue in all the android devices as the application heats the devices and shutdowns the application.

![heating](https://user-images.githubusercontent.com/39982680/121352733-c41e1200-c94a-11eb-9aea-0624e5f580b4.jpeg)
![heat](https://user-images.githubusercontent.com/39982680/121352834-e152e080-c94a-11eb-9c4e-97d5a3e06b38.jpeg)
# @igorwojda

**Comment by adrienrx** [comment]
Are you using a SurfaceView or a TextureView to render your preview ?

**Comment by UrielFrankel** [comment]
I changed the default config to solve this:
        OpenTokConfig.setPreferH264Codec(OpenTokConfig.PreferH264.ENABLE)

**Comment by vmeditab** [comment]
Facing same issue... After 15-20 minutes joining the session, phone is getting heat.

Using below dependency,

`com.opentok.android:opentok-android-sdk:2.23.1
`
Using below code,

```
Publisher.Builder(this)
            .name(getProviderJSONString())
            .resolution(Publisher.CameraCaptureResolution.MEDIUM)
            .frameRate(Publisher.CameraCaptureFrameRate.FPS_1)
            .build()
```

**Comment by igorwojda** [comment]
One for @adrienrx

**Comment by adrienrx** [comment]
I had that issue last year when I wanted to use TextureView in my app. Rolling it back to GLSurfaceView fixed the heating problem.
You probably did the swap to TextureView for the better handling of that component of android constraint. If you are struggling with the Z order, this is the line you need               `  ((GLSurfaceView) (publisher.getView())).setZOrderOnTop(true);`

**Comment by adrienrx** [comment]
Note that if you are using Relayed session, the impact on your phone is higher than if you rely on routed session. Especially with 4 participants.

**Comment by vmeditab** [comment]
I am using FrameLayout currently....

**Comment by adrienrx** [comment]
And you're not using useTextureViews is the SessionOptions right ?

**Comment by vmeditab** [comment]
I have a below code,

` mSession = Session.Builder(this, mSTRotAPIKey, mSTRotSessionId)
            .sessionOptions(object : Session.SessionOptions() {
                override fun useTextureViews(): Boolean {
                    return true
                }
            })
            .connectionEventsSuppressed(true)
            .build()
        mSession?.setSessionListener(this)
        mSession?.setSignalListener(this)`

@adrienrx

**Comment by adrienrx** [comment]
Yeah so you want to have the useTextureViews set to false to have the SDK provide GLSurfaceView

**Comment by vmeditab** [comment]
And what about `isHwDecodingSupported` and `isCamera2Capable`?

Will it be by default false or I have to change these methods as well?

**Comment by adrienrx** [comment]
I have tried to play with these in the past, my experience is, just don't play with those and leave it to their default value :rofl:

**Comment by vmeditab** [comment]
Okay one more thing I want to ask that why we can't use TextureView and why device will be get hitted if we use this? 

Just ask for the knowledge..

**Comment by adrienrx** [comment]
I literally have no idea, it could be the way the vonage renderer is built, or the way the textureview implementation is done. But the result is that the phone gets very hot and results in angry users. So I use GLSurfaceView.

**Comment by vmeditab** [comment]
By using GlSurfaceView, the icons of end call and others will be covered.

**Comment by adrienrx** [comment]
Yup, that's your new challenge now. GLSurfaceView isn't respecting the Z-Index of Android. I did struggle a bit to adapt my UI to it. 

![image](https://user-images.githubusercontent.com/4056555/191474919-11784aed-e9bb-4868-8c89-bbe3fdab24d0.png)

**Comment by UrielFrankel** [comment]
> By using GlSurfaceView, the icons of end call and others will be covered. I can see only the view of front camera.

FWIW You can overcome it with setZOrderMediaOverlay(true).
