### ISSUE TITLE
opentok SDK 

### ISSUE THREAD

**Issue by srinivasnumburi** [opentok/opentok-android-sdk-samples#390]
Hi Opentok team,
We plan to develop a video call application and we need to use our own signalling server and media server for experimentation  to do video calling and broadcast respectively. We are currently using AppRTC and Nginx Media server as our signalling server and media servers. We use Tokbox client side sdk for android and ioS and serverside sdk.  We would sincerely appreciate your support in resolving the below challenges:

1. Is it possible to create session id and tokens without connecting to opentok systems?
2. Is it mandatory to use apikey and secrete key supplied by tokbox? If so, when we use them we are unable to generate session ids and tokens when we are not connected to opentok. 
3. We need to send RGBA based camera frames between 2 connecting mobile phones. We mean to send a camera captured frame with transparent background over the network to other device. btw, we have some deep learning models to make the background transparent in a camera frame.
Looking forward to hear your response at the earliest.

**Comment by v-kpheng** [comment]
@srinivasnumburi, apologies for the belated reply.

Yes, you can create sessions and tokens without connecting to our platform.  More info here: https://tokbox.com/developer/sdks/node/.

Yes, you must use OT API keys and secrets.
