### ISSUE TITLE
Unable to share camera preview during screen sharing

### ISSUE THREAD

**Issue by UmarAlyas0078** [opentok/opentok-android-sdk-samples#391]
I have integrated openTok in my project and my requirement is to share all the content on the screen so to do that I have passed my root view (Constraint layout which has some other views and a androidx.camera.view.PreviewView) so while the screen sharing I am able to share other views but then I am not able to share the camera preview the user on the other side can see all the other views and sees a black screen instead of camera preview.

**Comment by kundanthe** [comment]
Why its closed ? Is this issue fixed ?

**Comment by v-kpheng** [comment]
This issue was closed because it was an aged issue.  If you can reproduce, please file again and we're happy to investigate.

**Comment by kundanthe** [comment]
@v-kpheng  still I am getting this issue camera preview is not showing when sharing screen.
