### ISSUE TITLE
Not working with  ONE PLUS devices?

### ISSUE THREAD

**Issue by formsworld** [opentok/opentok-android-sdk-samples#392]
SDK doesn't seems to work on an ONE Plus[Android] devices. On other devices it is working fine.

The issue here is, subscriber video not rendering to the server.

But other then ONE PLUS devices it is working fine.

**Comment by v-kpheng** [comment]
@formsworld, apologies for the belated reply.

Can you please try the most recent version of the SDK?  If the problem persists, please file another issue.  Thanks!
