### ISSUE TITLE
How can I get call duration of each participant in Multiparty Constraint Layout

### ISSUE THREAD

**Issue by AmjedAli** [opentok/opentok-android-sdk-samples#402]
Is it possible to check the talk time consumed by users using opentok?

**Comment by v-kpheng** [comment]
@AmjedAli, sorry, we don't have an API to determine call duration.  There are no near-term plans for it either.

If it helps, here's one approach that may work for you: https://stackoverflow.com/a/64588346.  Hope that helps.
