### ISSUE TITLE
Video call not working on Android 11 version devices

### ISSUE THREAD

**Issue by Akhil-1483** [opentok/opentok-android-sdk-samples#403]
SDK doesn't seems to work on an Android 11 version. On other versions it is working fine.

The issue here is, subscriber video not rendering to the app (it's looks like black screen when video call was started).

But other then OS version it is working fine.

**Comment by ashu8786** [comment]
I'm also facing the same issue. Have you guys found any solution yet?

**Comment by thekundankamal** [comment]
Yes, I am also getting this issue can anyone please help here..

**Comment by Akhil-1483** [comment]
> I'm also facing the same issue. Have you guys found any solution yet?

not yet still finding the solutions

**Comment by ankitgupta394** [comment]
After update opentox version with **"implementation 'com.opentok.android:opentok-android-sdk:2.21.3'"**  working fine in Android 11

**Comment by v-kpheng** [comment]
Thanks, @ankitgupta394, for helping out! 💪

Closing, since this was fixed by an updated version of the SDK.
