### ISSUE TITLE
audio is heard through the Earpiece after disconnecting the headset.

### ISSUE THREAD

**Issue by yinping-ge** [opentok/opentok-android-sdk-samples#406]
With Advanced-Audio-Driver-Java, there is an issue with audio output:

Steps to reproduce:
a) connect to a session with a wired headset plugged
b) unplug the headset

Expected behaviour:
The audio is routed back to the speakerphone "as it is the default output device".

Actual behaviour:
The audio is routed to the earpieces.

**Comment by adrienrx** [comment]
Try 2.21.2 :)

**Comment by v-kpheng** [comment]
Thanks, @adrienrx 💪 

Closing, since this was fixed in 2.21.2.
