### ISSUE TITLE
Expose method for changing video background color

### ISSUE THREAD

**Issue by victorkifer** [opentok/opentok-android-sdk-samples#411]
When you set video style to fit (`setStyle(BaseVideoRenderer.STYLE_VIDEO_SCALE, BaseVideoRenderer.STYLE_VIDEO_FIT)`) on `PublisherKit` or `SubscriberKit`, the video will be fit into the view and so it's possible to have black borders on some sides.

I would like to be able to change that color. IMO it makes sense to expose it via `PublisherKit`/`SubscriberKit` or `BaseVideoRenderer`. It seems like just storing it in renderer and using it in `GLES20.glClearColor();` method should do the trick.

**Comment by v-kpheng** [comment]
Thanks, @victorkifer, for this suggestion.

There's no plans for this API but that may change in the future.

CC'ing @Daniel085, since this is product request.
