### ISSUE TITLE
Null extracted folder for artifact: ResolvedArtifact

### ISSUE THREAD

**Issue by RanoshTarek** [opentok/opentok-android-sdk-samples#422]
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=com.vonage:webrtc:84.0.20, variant=com.vonage:webrtc:84.0.20 configuration compile, variantName=null, artifactFile=C:\Users\rana\.gradle\caches\modules-2\files-2.1\com.vonage\webrtc\84.0.20\693d4c04eea690be174ecd0d60dd80aa19456dd9\webrtc-84.0.20.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=projectname})

**Comment by rktalusani** [comment]
change gradle properties and increase the RAM

org.gradle.jvmargs=-Xmx4096m

**Comment by v-kpheng** [comment]
Thanks, @rktalusani 💪 

Closing, since this was fixed by a kind samaritan :-)

**Comment by javierbc121086** [comment]
Hello!, I currently have the same error, only from a React Native app. The error only occurs when trying to add an .aar to the project, otherwise it works correctly. (i am using react native version 0.72.5 and android studio 22.3.1 patch 2)
