### ISSUE TITLE
Opentok library contains references to the old support library that is deprecated

### ISSUE THREAD

**Issue by Zudoku** [opentok/opentok-android-sdk-samples#423]
Hello! 

Opentok library seems to contain references to the old android support library. 

> WARNING: [Processor] Library '.../com.opentok.android/opentok-android-sdk/2.21.4/f4eac4fa32dc22a05ee6dddde7bfb3f1a80ca97f/opentok-android-sdk-2.21.4.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
>  Example of androidX reference: 'androidx/annotation/Keep'
>  Example of support library reference: 'android/support/annotation/Nullable'

This is a very minor issue, but any possibility to have the library migrate fully into androidX? 😸

**Comment by v-kpheng** [comment]
Thanks, @Zudoku, for filing this issue.  It's on our radar, yes: https://jira.vonage.com/browse/OPENTOK-49339.  That said, we don't have an ETA to share.  Sorry.

Will keep you posted.

**Comment by v-kpheng** [comment]
Just wanted to share an update.  This should be fixed in the upcoming Android SDK 2.24.1 release.

**Comment by v-kpheng** [comment]
FYI, Android SDK 2.24.1 was released.  If you still see this issue, please let us know.  Thanks!
