### ISSUE TITLE
Showing green image after Live capture of subscriber view

### ISSUE THREAD

**Issue by raman-kumar-ha** [opentok/opentok-android-sdk-samples#426]
Using this https://github.com/opentok/opentok-android-sdk-samples/tree/main/Live-Photo-Capture-Kotlin
When i save screenshot of subscriber it shows green colour bitmap .

**Comment by v-kpheng** [comment]
Thanks, @raman-kumar-ha, for filing this.  We're tracking this internally as https://jira.vonage.com/browse/OPENTOK-49208.

**Comment by v-kpheng** [comment]
@raman-kumar-ha , I checked with someone on the team.  They're not able to reproduce this anymore, using the latest version of the SDK.

Can you please try again, please?  Thanks!
