### ISSUE TITLE
release build

### ISSUE THREAD

**Issue by fenngzui** [opentok/opentok-android-sdk-samples#428]
E/rtc: #
    # Fatal error in: ../../../../src/modules/utility/source/helpers_android.cc, line 74
    # last system error: 22
    # Check failed: !jni->ExceptionCheck()
    # Error during FindClass: com/vonage/webrtc/voiceengine/BuildInfo

**Comment by v-kpheng** [comment]
@adrienrx, nice meme :-)

Update rules can be found here: https://tokbox.com/developer/sdks/android/#proguard-rules-needed-by-the-vonage-android-sdk
