### ISSUE TITLE
Publisher onError: Error (Timed out while attempting to publish.) in publisher

### ISSUE THREAD

**Issue by kalpeshkanani** [opentok/opentok-android-sdk-samples#436]
D/opentok: [ERROR] otk_session_private.cpp:2938 - otk_session_stream_create_response Failed to complete publisher peer connection
 
 D/opentok: [ERROR] otk_messenger_v2.cpp:3727 - otk_messenger_v2_on_stream_create_response_implraptor sess is null or parsing ICE info failed.

D/opentok: [ERROR] raptor_message_v2.cpp:258 - content object does not exist or is not an object
 
 **onError: Error (Unable to Publish.) in publisher**
 
  Access denied finding property "persist.camera.legacy_perf"

**Comment by kalpeshkanani** [comment]
**plz update status**

**Comment by v-kpheng** [comment]
Thanks, @kalpeshkanani, for filing this issue.

What are the steps to reproduce?  What version of the SDK did you use?  Can you try to reproduce using the latest version please?

**Comment by v-kpheng** [comment]
Closing, given lack of steps to reproduce.  Please feel free to refile.  Thanks!
