### ISSUE TITLE
After enable video or voice during call stream not connect

### ISSUE THREAD

**Issue by saeed-lotfi** [opentok/opentok-android-sdk-samples#442]
**Describe the bug**
In the first connect Opnetok without enabling mic or camera and after enabling camera or mic nothing will change and voice or video will not show till use `subscribeToAudio = true` or `subscribeToVideo while = true ` while `hasVideo` or `hasAudio` is `true`
notice : it's just happen in first time

**To Reproduce**
- Connect devices as subscribe and publisher with out enabling mic or camera in publisher
- enable camera or mic in publisher 
- subscriber not receive stream 

Android 13

**Comment by devwithzachary** [comment]
Hello, what version of the SDK are you using? I'm not completely clear on the error you are seeing so if you're able to provide a minimum working example of the bug that will be a huge help. Thanks!

**Comment by saeed-lotfi** [comment]
I'm currently using the "2.21.5" version, which is fine, but after updating to the latest version, it no longer works.

**Comment by advaitsaravade** [comment]
This should be marked as fixed with the Feb 2023 release 2.24.2. The release notes have a point stating:

- This version fixes an issue where audio would remain muted for users under certain circumstances.

I tested it out and it seems to have fixed the issue.

**Comment by v-kpheng** [comment]
Thanks, @advaitsaravade.
@saeed-lotfi, I'm closing, since this was fixed in 2.24.2.
