### ISSUE TITLE
Audio not coming in screen recorder Android 

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#452]
**Describe the bug**
I am using screen recorder functionality to record live streaming screens on Android App, but I am not getting audio of the person who is publishing the stream.

**To Reproduce**
Start streaming and use a screen recorder.

**Expected behavior**
when we see the saved recording file then there was no audio.

**Screenshots**

**Additional context**
We are using custom audio driver for opentok.

**Comment by v-kpheng** [comment]
Thanks, @dev-android1, for letting us know about this issue.  Android SDK 2.24.2 was recently released.  Are you able to reproduce using that version of the SDK as well?

**Comment by dev-android1** [comment]
Yes, I am facing same issue in this release too.
My requirement is to record activity in which i am publishing & subscribing stream. So please help me how to resolve this issue.

**Comment by jintgeorge** [comment]
@dev-android1 Can you please check any settings with screen recorder. As per my knowledge we explicitly do not disable audio for any screen recording. Also you can look at the custom audio driver logs to see if anything is wrong.
