### ISSUE TITLE
Why do we need the android.permission.READ_PHONE_STATE ?

### ISSUE THREAD

**Issue by jrdaher** [opentok/opentok-android-sdk-samples#455]
**Describe the bug**
It's more of a question. I am wondering why open tok needs this permission. I have tried removing it via
`    <!-- <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove"/>-->`
and things work just fine. 

Would it be possible to remove it from open tok sdk in the future ?

Thank you !

**Comment by jintgeorge** [comment]
@jrdaher No plans to remove the phone state permission in near future. 
You may see issues when you accept an incoming phone call during opentok session is active.
