### ISSUE TITLE
onDisconnected not called SubscriberListener

### ISSUE THREAD

**Issue by tstefanovska** [opentok/opentok-android-sdk-samples#458]
**Describe the bug**
onDisconnected callback from SubscriberListener not fired when subscriber disconnects from session.

**To Reproduce**
Disconnect from session with subscriber.

**Expected behavior**
onDisconnected should be called.

**Screenshots**

**Device (please compete the following information):**
- sessionId, if applicable:
- Android SDK version: 
- OS and version: **Android 11**

**Comment by jintgeorge** [comment]
Hello @tstefanovska
