### ISSUE TITLE
Crash issue EglCore

### ISSUE THREAD

**Issue by wlTrunks** [opentok/opentok-android-sdk-samples#459]
**Describe the bug**
Where is a crashes in the sdk

**To Reproduce**
1.Start session
2.Start camera

**Expected behavior**
Not crashing

**Device (please compete the following information):**
- Android 12 [API 31] Galaxy A51 (SM-A515F) 
- OS and version:](com.opentok.android:opentok-android-sdk:2.23.1)

**Additional context**
`Last Exception Backtrace:
java.lang.RuntimeException java.lang.RuntimeException: invalid surface: null
0	com.opentok.android.grafika.gles.EglCore.a(SourceFile:0)
1	com.opentok.android.grafika.gles.a.a(SourceFile:0)
2	com.opentok.android.grafika.gles.WindowSurface.<init>(SourceFile:0)
3	com.opentok.android.TextureViewRenderer$Renderer.run(SourceFile:0)`
[STREAMLAYE-81-qppbHVZLOTMBpDCSyaZ-callstack.txt](https://github.com/opentok/opentok-android-sdk-samples/files/11329802/STREAMLAYE-81-qppbHVZLOTMBpDCSyaZ-callstack.txt)

**Comment by jintgeorge** [comment]
@wlTrunks Can you please try with the latest SDK version.

**Comment by alexmprog** [comment]
@jintgeorge Issue was reproduced on OpenTok Android SDK | Version/Revision: android-2.25.0/d4431ca9bcd213d5f2faa19289fa919cfeac7e97 --- same stacktrace:

```


java.lang.RuntimeException: invalid surface: null
--

1 |   | com.opentok.android.grafika.gles.EglCore.a (SourceFile:)
2 |   | com.opentok.android.grafika.gles.a.a (SourceFile:)
3 |   | com.opentok.android.grafika.gles.WindowSurface.<init> (SourceFile:)
4 |   | com.opentok.android.TextureViewRenderer$Renderer.run (SourceFile:)


```

**Comment by v-kpheng** [comment]
@alexmprog, the latest version is 2.25.2.  Can you try on that please?  Thanks!

**Comment by ivgvard** [comment]
Describe the bug:
Periodically appear error during start a video call. Added log screen from success and error case, if it help. 
<img width="948" alt="error" src="https://github.com/opentok/opentok-android-sdk-samples/assets/107874499/e8766095-89fc-47f8-acde-e268679bc83c">

<img width="604" alt="success" src="https://github.com/opentok/opentok-android-sdk-samples/assets/107874499/c44ff80e-1bb3-41cc-962f-28709d7dc7d8">

Devices:

    xiaomi:redmi:note-9-pro android:31
    version: opentok-android-sdk:2.25.2

    samsung:SM-A515F android:33
    version: opentok-android-sdk:2.25.2

    samsung:SM-G990B android:33
    version: opentok-android-sdk:2.25.2

    samsung:SM-S918B android:33
    version: opentok-android-sdk:2.25.2

    Sony:XQ-CC54 android:33
    version: opentok-android-sdk:2.25.2 


FATAL EXCEPTION: Thread-30


Process: PID:  
java.lang.RuntimeException: invalid surface: null
	at com.opentok.android.grafika.gles.EglCore.a(Unknown Source:30)
	at com.opentok.android.grafika.gles.a.a(Unknown Source:8)
	at com.opentok.android.grafika.gles.WindowSurface.<init>(Unknown Source:3)
	at com.opentok.android.TextureViewRenderer$Renderer.run(Unknown Source:16)

**Comment by vphuong1205** [comment]
I am facing the same issue here for some user from Play store with opentok-android-sdk:2.26.2
Please check it:
Exception java.lang.RuntimeException: invalid surface: null
  at com.opentok.android.grafika.gles.EglCore.a
  at com.opentok.android.grafika.gles.a.a
  at com.opentok.android.grafika.gles.WindowSurface.<init>
  at com.opentok.android.TextureViewRenderer$Renderer.run

Sample attributes:
[HONOR HNREA (HONOR 90)]
[Android 13 (SDK 33)]
