### ISSUE TITLE
Crash issue Camera2VideoCapturer

### ISSUE THREAD

**Issue by wlTrunks** [opentok/opentok-android-sdk-samples#460]
**Describe the bug**
Crash in the sdk when disable camera

**To Reproduce**
1. Start session
2. disable camera

**Expected behavior**
Not crashing

**Device (please compete the following information):**
- Android 13 [API 33]  A52 Droid (SM-A525F) 
- com.opentok.android:opentok-android-sdk:2.23.1

**Additional context**
`Last Exception Backtrace:
java.lang.IllegalStateException java.lang.IllegalStateException: Session has been closed; further changes are illegal.
0	android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:887)
1	android.hardware.camera2.impl.CameraCaptureSessionImpl.stopRepeating(CameraCaptureSessionImpl.java:418)
2	com.opentok.android.Camera2VideoCapturer.stopCapture(SourceFile:0)
3	com.opentok.android.Camera2VideoCapturer.onPause(SourceFile:0)
4	com.opentok.android.PublisherKit.onPause(SourceFile:0)
5	com.opentok.android.PublisherKit.update(SourceFile:0)
6	java.util.Observable.notifyObservers(Observable.java:177)
7	com.opentok.android.Session.onPause(SourceFile:0)`
[STREAMLAYE-81-qppbHVZLOTMBpDCSyaZ-callstack.txt](https://github.com/opentok/opentok-android-sdk-samples/files/11329864/STREAMLAYE-81-qppbHVZLOTMBpDCSyaZ-callstack.txt)

**Comment by DanielNovak** [comment]
Same issue in our code. Calling the `Publisher.publishVideo(...)` several times and switching between `true` and `false` will quickly cause the SDK to crash.
