### ISSUE TITLE
ML transitive dependency

### ISSUE THREAD

**Issue by emartynov** [opentok/opentok-android-sdk-samples#467]
**Describe the bug**
Update to OpenTok latest library. Check the license information of your dependencies. Find out the ML library that is transitive to OpenTok doesn't have any license information.

**Expected behavior**
Transitive dependency has license information.
Transitive dependency is optional.

**Comment by v-kpheng** [comment]
@emartynov, to confirm, are you saying that the license information for the ML library is missing and should be added?

**Comment by emartynov** [comment]
@v-kpheng correct, you can check latest pom file https://repo1.maven.org/maven2/com/vonage/mltransformers/3.0.7/mltransformers-3.0.7.pom

**Comment by emartynov** [comment]
Oke, maybe I'm wrong. I followed url mentioned in the pom and I found on the page next info:

```
License

 

Subject to Customer’s compliance with this Agreement, Vonage hereby grants Customer a limited, revocable, personal, non-exclusive, non-transferable, non-sublicenseable license until this Agreement or Customer’s Account is terminated (the “Term”) to (i) use the documentation and APIs Vonage makes available to Customer to create an original application that interfaces with the Services (“Customer Application”), and (ii) make the Services available to Customer’s end users (“End Users”) through the Customer Application. The foregoing license shall extend to Customer Affiliates, provided that such Customer Affiliates are acting via Customer’s Account and provided further that Customer remains jointly and severally liable for all acts and omissions of its Affiliates. An “Affiliate,” with respect to a Party, means any entity that controls, is controlled by, or is under common control with that Party.
```

**Comment by emartynov** [comment]
So basically it is some proprietary license. Let me pass it to our legal department.

**Comment by v-kpheng** [comment]
Thanks, @emartynov, for the heads up.  If possible, please share the feedback you back from Legal.  I'll let Product know as well.
