### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 

### ISSUE THREAD

**Issue by pomegra** [opentok/opentok-android-sdk-samples#472]
Describe the bug
If you publish video, unpublish video and publish again, the app crashes.
It works fine on 2.25.3

To Reproduce

Update App to 2.25.3

Android:
Google Pixel 3XL

F/libc    (10061): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x65626972637372 in tid 10865 (Thread-16), pid 10061 (sh.android.care)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/crosshatch/crosshatch:12/SP1A.210812.016.C1/8029091:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2023-08-03 14:32:39.544168922+0800
Process uptime: 0s
Cmdline: com.swedish.android.care
pid: 10061, tid: 10865, name: Thread-16  >>> com.swedish.android.care <<<
uid: 10347
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x65626972637372
    x0  7265626972637362  x1  0000007556c007cc  x2  00000073c2c30680  x3  00000072a2d6f288
    x4  0000000000000400  x5  00000073c2c306c2  x6  000000000000005d  x7  000000000000005d
    x8  412f2cf2423bd44c  x9  412f2cf2423bd44c  x10 00000073bdc7b000  x11 0000000000000450
    x12 0000000000000007  x13 3d72656269726373  x14 0000000000000010  x15 0000000000000000
    x16 00000070cbc602b8  x17 0000007556b65b40  x18 0000007213e9a000  x19 00000073c30506e0
    x20 00000073c3050760  x21 00000072a2d6f460  x22 00000070ca12f3b1  x23 00000070ca08ba8c
    x24 00000072edda8d90  x25 00000070ca16957b  x26 00000072fdcd4030  x27 00000073c2c30680
    x28 00000072a2d74000  x29 00000072a2d6f480
    lr  00000070ca6d9c00  sp  00000072a2d6f450  pc  00000070ca6f3274  pst 0000000060000000
backtrace:
      #00 pc 0000000000b5a274  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #01 pc 0000000000b40bfc  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #02 pc 0000000000b428a8  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #03 pc 0000000000b4c6b8  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #04 pc 0000000000b4cd68  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #05 pc 0000000000b413d4  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #06 pc 0000000000b6c7a0  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #07 pc 0000000000be8d64  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #08 pc 0000000000be8fe4  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #09 pc 0000000000bf46c4  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #10 pc 0000000000be94b0  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (uv_run+380) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #11 pc 0000000000b6cfd0  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #12 pc 0000000000b14288  /data/app/~~DmdCRhBvgQ22FVq5HvFibw==/com.swedish.android.care-jgYPc0iBC0rhXh_VVNBTOg==/base.apk![libopentok.so](http://libopentok.so/) (BuildId: c83427fab7ffc0c35f72246f35e1e113199cf64c)
      #13 pc 00000000000b1910  /apex/com.android.runtime/lib64/bionic/[libc.so](http://libc.so/) (__pthread_start(void*)+264) (BuildId: ba489d4985c0cf173209da67405662f9)
      #14 pc 00000000000513f0  /apex/com.android.runtime/lib64/bionic/[libc.so](http://libc.so/) (__start_thread+64) (BuildId: ba489d4985c0cf173209da67405662f9)
Lost connection to device.

**Comment by v-kpheng** [comment]
@pomegra, can you please clarify which version of the SDK this worked fine on?  It's not clear if it is fixed or broken in 2.25.3.  Also, does the crash only happen with the Pixel 3XL?  Or, does it happen for all devices?

**Comment by pomegra** [comment]
> @pomegra，你能澄清一下哪个版本的SDK可以正常工作吗？目前还不清楚它在2.25.3中是固定还是损坏。此外，崩溃只发生在Pixel 3XL上吗？或者，它发生在所有设备上吗？

Android: 2.25.3  It is used more on Pixel 3XL, other models are not sure

**Comment by goncalocostamendes** [comment]
@pomegra it is difficult to find the root cause because the stack trace is not symbolised. If the error is still reproducible in v2.26.0, please provide the symbolised stack trace [see](https://developer.android.com/ndk/guides/ndk-stack), or attach to the ticket the log file in _txt_ format
