### ISSUE TITLE
Publisher audio lost during long run - Android - 2.25.1

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#478]
When publisher is active for long time e.g. 5 min then publisher audio lost. we are facing this issue from  Android SDK 2.25.1

**Comment by v-kpheng** [comment]
@dev-android1, I'm going to close this, since it's missing a lot of important details.  Can you please refile and answer the questions in the Issue template: https://github.com/opentok/opentok-android-sdk-samples/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Thanks!
