### ISSUE TITLE
Audio distortion issue on 2.24.2 Android SDK

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#479]
We tested with Android SDK version - 2.24.2 and iOS SDK version - 2.26.0 and found that when publisher is from iOS side then in Android subscriber getting distorted audio if publisher is active for some duration.

**Comment by v-kpheng** [comment]
@dev-android1, when does audio get distorted?  How long does the session need to last for that to happen?  Also, one which devices can you reproduce this with?

It'll help if you answer the questions in this template: https://github.com/opentok/opentok-android-sdk-samples/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Thanks!
