### ISSUE TITLE
iOS app crashing on SDK version 2.25.3

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#480]
Hi Team,

we have our iOS app at 2.18.1 and it was fine. when we upgraded to 2.25.3 & 2.26.0 it started crashing.
I am attaching logs. Please let us know how we can resolve this.

[Log_1.txt](https://github.com/opentok/opentok-android-sdk-samples/files/12731674/Log_1.txt)
[Log_2.txt](https://github.com/opentok/opentok-android-sdk-samples/files/12731677/Log_2.txt)
[Log_3.txt](https://github.com/opentok/opentok-android-sdk-samples/files/12731678/Log_3.txt)

Thanks

**Comment by v-kpheng** [comment]
@dev-android1, I'm going to close this, since it's missing a lot of important details.  Can you please refile and answer the questions in the Issue template: https://github.com/opentok/opentok-android-sdk-samples/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Thanks!
