### ISSUE TITLE
Publisher video freeze on app resume

### ISSUE THREAD

**Issue by dev-android1** [opentok/opentok-android-sdk-samples#481]
we are having 2 publisher in Android. One is publishing audio all time throughout app lifecycle. Another one publish video & audio when required on button click. when we start publishing from 2nd publisher then we turn off audiopublisher1 and start avpublisher2. now we put app in background and resume app then publisher2 doesn't resume video.

**To Reproduce**
Take 2 publisher - publisherAudioOnly & publisherAudioVideo . publish Audio via publisher1 and after sometime pause publisher1 and start publisher2 with audio video. now put app in background and resume app. video is freezed.

**Expected behavior**
video should not be freezed

**Screenshots**

**Device (please compete the following information):**
- sessionId, if applicable:
- Android SDK version: 
- OS and version:

**Additional context**

**Comment by v-kpheng** [comment]
@dev-android1 , which version of the Android SDK were you able to reproduce on?  Can you reproduce on 2.26.1?  Also, which devices can you reproduce with?
