### ISSUE TITLE
For BackgroundBlur feature with custom radius, application starts lagging

### ISSUE THREAD

**Issue by WCRohit** [opentok/opentok-android-sdk-samples#496]
**Describe the bug**
Hi, 

Found some issues, we get when trying the Segmentation feature of the OpenTok.

- For "BackgroundBlur", if we set "radius" value as custom, then the application becomes laggy. 
- For "BackgroundBlur", Support for setting the colour(Black or White) of blur is not available.

**Additional context**
The main issue is with BackgroundBlur with custom radius, the application becomes very laggy. We tried setting it to 90 and 100. In both cases faces the lagging issue.

Thanks

**Comment by goncalocostamendes** [comment]
@WCRohit which version of OpenTok lib are you using? There have been some improvements on the latests versions

**Comment by WCRohit** [comment]
@goncalocostamendes We are using 2.27.0 version of OpenTok. Thanks

**Comment by goncalocostamendes** [comment]
@WCRohit with which device and which resolution did you experienced lagging?

**Comment by WCRohit** [comment]
@goncalocostamendes We set the resolution to HIGH(CameraCaptureResolution.HIGH). Also below is the details on which we face the issue.
1. Google Pixel 6 
Android Version 13

2. Motorola One Fusion+ (Model Number: XT2067-3)
Android Version 11

Thanks

**Comment by goncalocostamendes** [comment]
@WCRohit please note that the blur algorithm complexity is O(R^2 * W * H) where:
 - R: blur radius
 - W: input width
 - H:  input height

Meaning increasing radius imply exponential more time processing.

As such, I recommend using a lower custom radius value or going with the **High** or **Low** pre-defined values where no lagging is visible.

I will be closing the ticket. Please re-open it if necessary.

**Comment by goncalocostamendes** [comment]
@WCRohit please note that the blur algorithm complexity is O(R^2 * W * H) where:
 - R: blur radius
 - W: input width
 - H:  input height

Meaning increasing radius imply exponential more time processing.

As such, I recommend using a lower custom radius value or going with the **High** or **Low** pre-defined values where no lagging is visible.

I will be closing the ticket. Please re-open it if necessary.

**Comment by goncalocostamendes** [comment]
@WCRohit in regards to your request for a black blur, I raised the feature request with the Product Team, but there is no prediction when it will be done or even if it will be done.

The best solution for it is to use insertable streams and create your own transformer. More info here https://tokbox.com/developer/guides/vonage-media-processor/android/#:~:text=Creating%20a%20custom%20video%20transformer

**Comment by WCRohit** [comment]
@goncalocostamendes Sorry, I didn't find any way in which multiple publishers can be created. On initialising 2nd publisher the application is getting crashed. 
Also, as you suggested we found that multiple subscribers are possible with multiple streams. 

Can You please share any document reference or Github example related to this? 

Thanks
