### ISSUE TITLE
[ERROR] PublisherKit Error: Unable to Publish.

### ISSUE THREAD

**Issue by DamienLeon** [opentok/opentok-android-sdk-samples#498]
I get the following error when trying to implement this on Android and calling the code via Flutter Platform channel:

```
[ERROR] otk_peer_connection_common.cpp:1000 - audio_track initialiser - error in start_capturer -1
[ERROR] otk_messenger_v2.cpp:3782 - otk_messenger_v2_on_stream_create_response_implraptor sess is null or parsing ICE info failed.
[ERROR] raptor_message_v2.cpp:258 - content object does not exist or is not an object
[ERROR] otk_session_private.cpp:2726 - otk_session_stream_create_response Failed to complete publisher peer connection
```

I'm currently on OpenTok Android SDK | Version/Revision: android-2.27.0/4edbd848cc26eda2eea6c2ff15c6a14d4eae8725

I can see that an issue was opened and closed without any solution on a similar problem. #436 
Also, I tried running the example code given here with the above mentioned version as well as Version/Revision: android-2.22.2/c13b016d204367ea782966d6c6a822ef731a2f38 and get the same error. I tested this on multiple devices too.
[https://github.com/Vonage-Community/sample-video-flutter-app/blob/main/android/app/src/main/kotlin/com/vonage/tutorial/opentok/opentok_flutter_samples/one_to_one_video/OneToOneVideo.kt](url)

Any help on resolving this is appreciated.

**Comment by DamienLeon** [comment]
Also, I tried running the example code with the same version as the one mentioned above and get the same error. I tested this on multiple devices too.

**Comment by v-kpheng** [comment]
@DamienLeon, for issues with Flutter, please file a report on https://github.com/Vonage-Community/sample-video-flutter-app instead.  If you're able to reproduce using one of the sample apps listed here, please do share the details.  Thanks!

**Comment by DamienLeon** [comment]
@v-kpheng Everything works fine from Flutter's end. I am successfully able to call the native code using Platform channels. The issue arises when I initialise the publisher object to connect to a session. Thanks for the reply.

**Comment by v-kpheng** [comment]
@DamienLeon, apologies for the belated reply.  I understand that the issue is reproducible using the Flutter sample app.  That said, to confirm, you're able to produce using an Android SDK sample app too?  If so, which one?
