### ISSUE TITLE
App is crashing always in dubai zone specific devices only, any idea?

### ISSUE THREAD

**Issue by PrinceGoyal** [opentok/opentok-android-sdk-samples#500]
App is crashing always in dubai zone specific devices only.
In indian zone tested so may devices video call is working fine, but all devices in dubai zone getting crash once vonace is inilialized in the app

**Comment by v-kpheng** [comment]
@PrinceGoyal, what devices did you use?  Also, what versions of the SDK did you use?  Can you reproduce using the latest version?

Lastly, which sample app did you use to reproduce this issue?

**Comment by beHaze** [comment]
We haven't heard back from you for a while so we're closing this issue for now. Please, reach out if you still need help.
