### ISSUE TITLE
Publisher custom video renderer shows video with inverted colour only

### ISSUE THREAD

**Issue by WCRohit** [opentok/opentok-android-sdk-samples#501]
**Describe the bug**
In my application, we want to get publisher frame buffer to be used to draw skeleton using MLKit. For this as per my understanding we have to use Custom Video Renderer and from this class "onFrame(frame: Frame)" function we will get frame buffer and use the buffer for getting image. The issue is when we use the CustomVideoRenderer from examples of OpenTok, the video we gets has inverted colour.

**Expected behavior**
Expected behaviour is in case if we can get a custom renderer with normal video for Publisher class.

**Additional context**
Additionally, are we doing anything wrong for getting Publisher Frame? Also, I am not proficient in OpenGL implementation at all, if you can give example for "GLSurfaceView.Renderer" implementation.

Thanks a lot in advance.

**Comment by WCRohit** [comment]
Hi, I guess the issue is coming because of the YUV format of Frame Buffer. What I have tried at my end is using "io.github.crow_misia.libyuv" library to convert YUV format to ArgbBuffer format. But the issue is still same with green background in foreground. Can You please help on this?
Thanks

**Comment by v-kpheng** [comment]
@WCRohit , just checked up with the team, the inverting was intentional.  Reason being, we wanted the "custom" part of the rendering to be evident.

**Comment by WCRohit** [comment]
@v-kpheng Thanks for your reply, Understood the reason. Closing the ticket.
