### ISSUE TITLE
BUG: Speaker is used instead of bluetooth earphones after mute/unmute

### ISSUE THREAD

**Issue by eldarovich99** [opentok/opentok-android-sdk-samples#505]
**Describe the bug**
Speaker is used instead of bluetooth earphones after mute/unmute

**To Reproduce**
1. Connect to a call with bluetooth earphones.
2. Toggle mute and unmute

**Expected behavior**
Bluetooth headphones are used in the call.

**Device (please compete the following information):**
- sessionId, if applicable:
- target Android SDK version: 34
- OS and version: Android 14, TokBox version: 2.27.1

**Comment by v-kpheng** [comment]
We're tracking this internally: https://jira.vonage.com/browse/VIDCS-2266.

**Comment by eldarovich99** [comment]
The issue was resolved after I tried AdvancedAudioDevice which you suggested to me. Please close the issue
