### ISSUE TITLE
Crash when using an other JNI libs + OpenTok

### ISSUE THREAD

**Issue by StanKocken** [opentok/opentok-android-sdk-samples#80]
If I want to add another library (like [card.io](https://github.com/card-io/card.io-Android-SDK)), OpenTok won't work anymore.
The cause of the crash is a JNI UnsatisfiedLinkError. Because another library like Card.io provide a .so for each architecture but OpenTok only for armeabi, the Android platform won't look into the armeabi folder.

Architecture OpenTok + Card.Io (into the APK compiled):

```
lib
  arm64-v8a
    libcardioDecider.so
    libcardioRecognizer_tegra2.so
    libcardioRecognizer.so
    libopencv_core.so
    libopencv_imgproc.so
  armeabi
    libcardioDecider.so
    libopentok.so
  armeabi-v7a
    libcardioDecider.so
    libcardioRecognizer_tegra2.so
    libcardioRecognizer.so
    libopencv_core.so
    libopencv_imgproc.so
  mips
    libcardioDecider.so
  x86
    libcardioDecider.so
    libcardioRecognizer_tegra2.so
    libcardioRecognizer.so
    libopencv_core.so
    libopencv_imgproc.so
    libopentok.so
  x86_64
    libcardioDecider.so
    libcardioRecognizer_tegra2.so
    libcardioRecognizer.so
    libopencv_core.so
    libopencv_imgproc.so
```

With only OpenTok:

```
lib
  armeabi
    libopentok.so
  x86
    libopentok.so
```

My question is: is it possible to provide the .so for each architecture? Or is there another way to have both library working together?

Thanks

**Comment by alexsorokoletov** [comment]
Due to the fact OpenTok doesn't support 64bit the app will crash if you have 64 bit enabled. Android OS loads all libraries from one folder, so if it will start loading anything from arm64-v8a then it will also look there for opentok which will be missing.

Until there is OpenTok supporting Android 64 bit you should just disable 64 bit in your project. You can do it using following steps: http://stackoverflow.com/a/30799825/883738

**Comment by robjperez** [comment]
Currently the sdk supports arm64, so this should be fixed.
Please reopen it if you are still having problems.

**Comment by archick12** [comment]
Sorry, for stupid question.
What about x86_64? 
I downloaded opentok-android-sdk-2.13.0 and wasn't able to find "libopentok.so" for the "x86_64" architecture. Do you plan to add support for this architecture?

```
$ ls -l jni/

arm64-v8a
armeabi
armeabi-v7a
x86

$ ls -l jni/arm64-v8a/
libopentok.so
```
