### ISSUE TITLE
Codes Doesn't Work On Eclipse

### ISSUE THREAD

**Issue by brnxprz** [opentok/opentok-android-sdk-samples#95]
I'm a student searching for a way how to screen share pc screen to phone like screen sharing. It would be nice if someone would guide me how to. Thank You!

**Comment by marinaserranomontes** [comment]
You can find the screensharing component here: https://github.com/opentok/screensharing-annotation-acc-pack I hope it helps you.

**Comment by brnxprz** [comment]
THANK YOU!
