### ISSUE TITLE
Use of sample BasicCustomVideoRenderer class

### ISSUE THREAD

**Issue by PorridgeBear** [opentok/opentok-android-sdk-samples#96]
The verbatim use of the BasicCustomVideoRenderer set onto the publisher (in order to use the saveScreenshot method:

`mPublisher.setRenderer(new BasicCustomVideoRenderer(mContext));`

leads to the publisher thumbnail bottom right not being displayed on top of the subscriber view. 

Commenting out the setRenderer line above (thereby making the Publisher use the internal DefaultVideoRenderer) makes the publisher thumbnail render on top of the subscriber.

**Comment by robjperez** [comment]
Opentok Subscribers and Publishers are using GLSurfaceViews to render its contents. 
The sample code `5.Live-Photo-Capture` seems to work fine, but sometimes, (depending on how the views are managed by the layout) the z-index can be done in a different way.

You can set the order explicitly by calling this:
```java
((GLSurfaceView)mPublisher.getView()).setZOrderMediaOverlay(true);
```
